### ISSUE TITLE
Icu types

### ISSUE THREAD

**Issue by alexandreliborio** [MIT-LCP/mimic-code#100]
Please, help me with abbreviations of these ICU types:
CCU	: coronary care unit
CSICU: Cardiovascular ICU?	
CTICU: ???
CVICU: Cardiovascular ICU
MICU: Medical ICU
MSICU: ?????
NSICU: ????
SICU: surgical ICU
TSICU: ????

**Comment by tompollard** [comment]
Hi Alexandre, it looks like you are using an older version of MIMIC-III because the abbreviations have been simplified in the current version (v1.3), but I have added details below to answer your question:

CCU : Coronary Care Unit
CSICU: Cardiac Surgical Intensive Care Unit
CTICU: Cardiothoracic Intensive Care Unit
CVICU: Cardiovascular Intensive Care Unit
MICU: Medical Intensive Care Unit
MSICU: Medical/Surgical Intensive Care Unit
NSICU: Neuro/Surgical Intensive Care Unit
SICU: Surgical Intensive Care Unit
TSICU: Trauma Surgical Intensive Care Unit
