### ISSUE TITLE
Is there any chest x-ray report in mimic database? How to find it?

### ISSUE THREAD

**Issue by wyyyzw** [MIT-LCP/mimic-code#1067]
Is there any chest x-ray report in mimic database? How to find it?

**Comment by wyyyzw** [comment]
> Yes, there is a MIMIC-IV-CXR module available, see the tables section of the website: https://mimic.mit.edu/iv/datasets/cxr/ . You can also access this data via BigQuery. See the access section on the website for more details: https://mimic.mit.edu/iv/access/ . Please note that we are in the process of updating the website so these links may change soon.

Thank you for your assistant. Can the cxr-record-list.csv.gz file, the cxr-study-list.csv.gz and the mimic-cxr-reports.zip be installed through PostgreSQL (I can't find the relevant files and codes in github)? And if a large number of study_id or dicom_id are known in a study design, how to batch download image files (.dicom)?

**Comment by briangow** [comment]
Yes, a procedure similar to that used for [MIMIC-IV](https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iv/buildmimic/postgres) can be used to add the MIMIC-CXR tables to a local Postgres database.  Unfortunately, there aren't any scripts on Github for this yet.  I have created an issue to address this.  You can track the progress of that issue here: #1068 .  

Regarding downloading specific image files if you know the `dicom_id`.   You can use the wget command as mentioned in the Files section of the [MIMIC-CXR project](https://physionet.org/content/mimic-cxr/2.0.0/). You can download particular files by passing the file-path and file-name: `wget -r -N -c -np --user USERNAME --ask-password https://physionet.org/files/mimic-cxr/2.0.0/file-path/file-name`.  Downloading large files can be slow with this method though.  Alternatively, it should be faster to download files from the Google Cloud Bucket. However, you will need to pay the egress cost to download from the Google Cloud Bucket.  You can adapt the MIMIC-IV Google Cloud Bucket download procedure [here](https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iv/buildmimic/bigquery/README.md) to work with MIMIC-CXR by changing the path as appropriate.

**Comment by wyyyzw** [comment]
> Yes, a procedure similar to that used for [MIMIC-IV](https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iv/buildmimic/postgres) can be used to add the MIMIC-CXR tables to a local Postgres database. Unfortunately, there aren't any scripts on Github for this yet. I have created an issue to address this. You can track the progress of that issue here: #1068 .
> 
> Regarding downloading specific image files if you know the `dicom_id`. You can use the `wget` command as mentioned in the Files section of the [MIMIC-CXR project](https://physionet.org/content/mimic-cxr/2.0.0/). You can download particular files by passing the file-path and file-name: `wget -r -N -c -np --user USERNAME --ask-password https://physionet.org/files/mimic-cxr/2.0.0/file-path/file-name`. Downloading large files can be slow with this method though. Alternatively, it should be faster to download files from the Google Cloud Bucket. However, you will need to pay the egress cost to download from the Google Cloud Bucket. You can adapt the MIMIC-IV Google Cloud Bucket download procedure [here](https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iv/buildmimic/bigquery/README.md) to work with MIMIC-CXR by changing the path as appropriate.

Thank you for your assistant. I have downloaded all files by wget. However, is there a way for us to accurately and quickly extract the target CXR. In other words, if we know some study patients we want, how to automatically filter out the CXR images of these patients in the form of codes, instead of manual method one by one.

**Comment by briangow** [comment]
I'm not sure if I fully understand your question.  If you want to target specific images based on `dicom_id` you can create a table from a SQL query (run on the MIMIC-CXR database).  You can then use a script (in the programming language of your choice) which uses the resulting table to target specific DICOM's.

**Comment by SichengH** [comment]
MIMIC-IV-CXR and MIMIC-IV can be linked with subject_id. I would suggest finding the target population with MIMIC-IV and select the CXR database based on subject_id and time.
