### ISSUE TITLE
Primary diagnoses for Elixhauser Comorbidity

### ISSUE THREAD

**Issue by shalmalijoshi** [MIT-LCP/mimic-code#113]
I am using elixhauser's comorbidity index to identify the chronic conditions. Specifically, this script: https://github.com/MIT-LCP/mimic-code/blob/master/comorbidity/postgres/elixhauser-ahrq-v37-with-drg.sql.

I noticed that the script ignores the primary diagnoses code, which would be useful for to have since we require the primary chronic condition for our analyses. Is it appropriate to calculate the elixhauser's index without ignoring the primary conditions by simply modifying the script  to use diagnoses codes with sequence number 1 as well?

Also, if anyone could elaborate on the significant differences between the old and the new versions of calculating elixhauser's index (we have the old version/script from github which ignores sequence numbers), that would help too.

**Comment by alistairewj** [comment]
As the script is looking for comorbidities, it excludes the primary
diagnosis, since by definition this is the primary condition/reason for
admission to the hospital and thus not a comorbidity. I believe this is the
same logic used in the publishing article.

It depends which old version you are referring to - I think I've written 10
versions of Elixhauser, and I'm sure there were more written by other
people! :)
