### ISSUE TITLE
inputevents_mv wrong amountuom or wrong amount

### ISSUE THREAD

**Issue by ngageorange** [MIT-LCP/mimic-code#116]
Hello,

In trying to calculate the amount of morphine or midazolam a patient has had in their first day, I've stumbled upon an error in the table.

Take this row:

`select * from inputevents_mv WHERE icustay_id = 290505 AND itemid = 221668 `

The amount is 0.00075 and the amountuom is mg. However, the infusions is at 0.5mg/hr for 1.5 hours so it should be 0.75mg...implying the amount is incorrect.

Or the amount unit of measurement should be g instead of mg.

I've found this to be true for morphine and midazolam so far, but perhaps this is a wider issue regarding drug infusions?

Best Wishes,

Ahmed

**Comment by alistairewj** [comment]
Good spot. Just reviewed the code, looks like volume is always output in base units. So no matter what is listed in the unit of measurement column, volume is output in the base unit - for weights the base unit is grams so in this case volume is stored in grams instead of milligrams. Use the rate for now and we'll fix it in the next release.

**Comment by ngageorange** [comment]
Brilliant! Thanks 👍

**Comment by alistairewj** [comment]
This should be fixed in v1.4 - feel free to re-open if you find any issues. Thanks for the report!
