### ISSUE TITLE
Missing caregiver ids (CGID) of discharge summaries in MIMIC-III

### ISSUE THREAD

**Issue by joe32140** [MIT-LCP/mimic-code#1313]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I am interested in analyzing clinical notes of difference doctors but I found that all discharge summaries have no CGID. I assume that a discharge summary should be mainly written by a doctor, so the CGID of a discharge summary is trackable but missing in the MIMIC-III dataset. 

Will it be possible to release a new version of `NOTEEVENTS.csv` where we can have CGIDs for discharge summaries?

**Comment by alistairewj** [comment]
`cgid` specifically is an ICU level concept derived from MetaVision/CareVue. For the discharge summaries, we will not be updating those in MIMIC-III. We do have an author name for the discharge summaries we plan to release for MIMIC-IV, but we haven't converted them into deidentified IDs for publishing (partly because we haven't managed to get the notes out yet.. which is the priority!).

**Comment by joe32140** [comment]
Thank you for the reply. Looking forward to future MIMIC-IV notes release!
