### ISSUE TITLE
Link between labevents and poe table?

### ISSUE THREAD

**Issue by lkervezee** [MIT-LCP/mimic-code#1378]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I'm wondering if there's a way to link the 'poe' table to labevents, i.e. is there a way to know which poe_id with order_type == "Lab" belongs to any given labevent_id? Or is there another way to find out when a lab test was ordered?

**Comment by alistairewj** [comment]
There's no link as far as I'm aware - the identifier for poe was not in the labevents table (and vice-versa).

**Comment by whiskey0504** [comment]
> There's no link as far as I'm aware - the identifier for poe was not in the labevents table (and vice-versa).

Hi, I'm also interested in retrieving when a lab is ordered from the poe table, and wonder if there is any update on this. Right now it looks like even if I track down to the same stay_id and same order_provider_id, there is no exact way to match each lab event to order time. Relying on the ordering of lab events can be inaccurate since a lab might be the first to be ordered but second to be collected. I wonder if there is any other way around this. Thanks!
