### ISSUE TITLE
MIMIC-IV Patients

### ISSUE THREAD

**Issue by JBarsotti** [MIT-LCP/mimic-code#1512]
I've only recently started using MIMIC-IV and think it is fantastic!

I'm sorry if this is a really stupid question, but are all patients in MIMIC-IV only from those admitted to the ICU or Emergency Department? I know that there are separate modules for both ED and ICU, as well as HOSP. Currently my understanding is that HOSP contains hospital-wide information, not just ED and ICU data. In order to have data in HOSP, do patients have to come from the ED or ICU? I took a screenshot of a plot you all created for your _Nature_ article. Can the people in the "Hospital Admissions" be from places other than the ED and ICU?

![image](https://user-images.githubusercontent.com/75189583/228377709-9b7459f9-5b63-4a9e-bd3e-3a5551d29220.png)

Thanks for all your efforts creating this dataset.

**Comment by alistairewj** [comment]
Our process is essentially: 

1. Identify patients. This is done by a hospital based filter to identify patients who were admitted to either (1) the emergency department or (2) a critical care unit **at any point in time**.
2. Filter transfers within the hospital to this list of patients, and to occur between the time period of data collection (2008 - 2019).
3. Identify ICU admissions from the hospital maintained record of ward transfers by checking the assigned cost center of the ward and whether we have data in the MetaVision system for the patient (which is in place in the ICU).

So, because we don't explicitly filter hospitalizations based on ED/ICU, yes hospital admissions can occur from places other than the ED and ICU. For example see `hadm_id = 27683372` which is a surgical admission.

**Comment by JBarsotti** [comment]
Thank you for such a thorough reply! You are a wonderful person for making all this freely available, especially for poor graduate students like me. :)

**Comment by alistairewj** [comment]
Happy to!
