### ISSUE TITLE
problem in obtaining waveforms of a specific ICD code

### ISSUE THREAD

**Issue by mahdiehhhh** [MIT-LCP/mimic-code#1569]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello
I have encountered a problem regarding the connection between **waveforms** and the information on **patient's ICD codes**.

Using _ICD 9 code 53501_, for example, I am going to _extract it's waveforms_. 
In order to accomplish this, I used the DIAGNOSES_ICD table and obtained the corresponding subject_id and HADM_ID. 
I know that I should then get the corresponding waveform with the help of the intime column from the ICUSTAYS table, but I have a problem because there are multiple ICD codes for each subject, and I must have the **ICUSTAY_ID column in the DIAGNOSES_ICD** dataframe **in order to get the waveform for each code.**

_In other words_, I must follow these steps, **but** I do not have the ICUSTAY_ID.
1- Finding the ICUSTAY_ID associated with the desired ICD code
2- Finding the waveform based on the ICUSTAY_ID obtained in step

I'm hoping you see the issue. 
Is there a solution to this problem?

![Inked2](https://github.com/MIT-LCP/mimic-code/assets/89372686/5f959403-ac4d-4433-a9ca-7b1f60243848)

**Comment by mahdiehhhh** [comment]
@alistairewj

**Comment by alistairewj** [comment]
There are potentially:

- many `icd_code` per `hadm_id`
- many `icustay_id` per `hadm_id`
- many waveforms for each `icustay_id`

Technically, this can be accomplished by aggregating in each step.

- for `icd_code` to `hadm_id`, you could check for *any* presence of the icd code (very often done with `MAX(CASE WHEN icd_code = '53501' THEN 1 ELSE 0 END) AS has_icd_code`)
- for `icustay_id` to `hadm_id`, see below, but you could simply assign all `icustay_id` within an `hadm_id` as having the code
- for waveforms, you would then do the same

This would end up giving you a query something like this:

```
SELECT i.icustay_id, i.hadm_id, MAX(CASE WHEN icd_code = '53501' THEN 1 ELSE 0 END) AS has_icd_code
FROM mimiciii.icustays i
INNER JOIN mimiciii.admissions a
ON i.hadm_id = a.hadm_id
INNER JOIN mimiciii.diagnoses_icd dx
ON a.hadm_id = dx.hadm_id
GROUP BY i.icustay_id, i.hadm_id
```

You'd then need to align the waveforms based on the `intime`, `outtime`, and time of the matched waveform.

However, this is making some assumptions. It's assuming that the billed ICD code for the hospitalization is valid for each ICU stay. This may be OK in some cases, but you can very easily imagine situations where an ICD code is not valid for an entire ICU stay. For example, the code for acute kidney injury is 584.9. This means that the patient had acute kidney injury sometime during their hospital stay, but you don't know when. Since the waveform occurs only for a subset of their hospital stay, it very well may be that you extract a waveform "associated" with the ICD code for 584.9, but that doesn't have anything related to acute kidney injury. This is a fundamental limitation of hospital based ICD codes: there's no time component for them.

Hope that helps!

**Comment by mahdiehhhh** [comment]
Thank you so much for taking the time to give me advice. Definitely, I will
read what you said carefully and act accordingly
regards


‫‪Alistair Johnson‬‏ ***@***.***‬‏> در تاریخ یکشنبه ۲۵ ژوئن
۲۰۲۳ ساعت ۲۲:۰۶ نوشت:‬

**Comment by mahdiehhhh** [comment]
**Hello again** @alistairewj
I tried to carefully read the steps you mentioned and get their tips, although I almost did not understand the whole code that you wrote in query language.
 As far as I understand, you used "**icustays**" , "**admissions**" , "**diagnoses_icd**" tables , but in none of the tables, there are two columns "**_icustay_id_**" and "**_hadm_id_**" next to each other so that I can match them.
