### ISSUE TITLE
list of available lab values

### ISSUE THREAD

**Issue by 22csnyder** [MIT-LCP/mimic-code#169]
Hi, (I think this is the right place for this question)

I'm trying to decide if MimicIII is the right dataset for me before I go through the process of getting it. To do this I need a detailed sense of what lab values are actually available. The website gives some idea under "mimictables" but lacks details on what labs are actually measured. Surely a list of available datatypes could be provided without endangering health information.

many thanks
chris

**Comment by tompollard** [comment]
@22csnyder Hi Chris, thanks for posting here. What lab values are you looking for? If you let me know, I'd be happy to run a quick query.

> Surely a list of available datatypes could be provided without endangering health information.

Posting a list of lab concepts is something that we could consider (essentially the `d_items` table), though doing this isn't entirely without risk because the list could potentially contain free text added by caregivers.

**Comment by tompollard** [comment]
Just as a side note, if the laboratory tests that you are interested in are typically measured for patients in the ICU, then they are likely to be documented in MIMIC-III.

**Comment by 22csnyder** [comment]
@tompollard Thanks for the fast response. I wish I had something concrete you could query for. I was more in search of the right medical context to apply a high level idea. Anyway, I appreciate that there could be trade-offs in listing d_labitems, and I appreciate maintenance of this dataset.

I'll probably just go through the process and try to get access

Chris

**Comment by tompollard** [comment]
Thanks Chris, and all the best with this research.
