### ISSUE TITLE
Overlapping ICU stay with discrepancies

### ISSUE THREAD

**Issue by rustamzh** [MIT-LCP/mimic-code#1726]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi, I have found an overlapping ICU stays for the same patient:

![image](https://github.com/MIT-LCP/mimic-code/assets/8539796/ce3b22d5-6f92-416a-b715-d1fc9b17b86f)

Both ICU visits have separate vital sign measurements. For example, at 2185-06-12 18:00:00.000, in one of the icu stays SpO2 is 93 in the other is 98

I am working with MIMIC IV v1.0 so it might be an old version issue

**Comment by alistairewj** [comment]
Yes this is fixed in v2.0. If you see distinct `hadm_id` for the same patient with overlapping time, they usually unfortunately died and have had a second hospitalization created to facilitate donation of their organs (it's just how they track it at the hospital). We removed the organ donor admissions in v2, so for this patient the second hospitalization is no longer in the database.
