### ISSUE TITLE
Out of Hospital Mortality in MIMIC-IV v3.0

### ISSUE THREAD

**Issue by JZL429** [MIT-LCP/mimic-code#1798]
Hi,

In the newest v3.0 update you said that 'Out of hospital mortality is available for up to 1-year post hospital or ED discharge'. I was wondering where do you have this information in the database? Thank you very much for the help!

**Comment by alistairewj** [comment]
The `dod` column in the patients table will have the date of death. If the patient is alive at the time of data collection, the column will be null. If the patient died more than 1 year after their last discharge (either ED or hospital), then this column will be NULL. Therefore you can use it for 1-year post hospital discharge mortality.

Since patients have more than one admission, the `dod` column is often more than 1-year after any given admission, but it cannot be more than 1-year after their last admission. This limitation of follow up is done for deidentification purposes.
