### ISSUE TITLE
MIMIC-III DB Schema/ERD request

### ISSUE THREAD

**Issue by postgres-newbie** [MIT-LCP/mimic-code#183]
Hello, 

Just as you had uploaded a nice manual for MIMIC-II (https://mimic.mit.edu/archive/mimic-ii-guide.pdf), could you please upload one for MIMIC-III with an entity relationship diagram?

Thanks much!!

**Comment by tompollard** [comment]
@postgres-newbie Hi Krupa, would you be able to take on the task of generating the diagram?  If you post it in this thread then we can then distribute it on the MIMIC website.

**Comment by postgres-newbie** [comment]
![mimic_iii_foreign_keys_nogroups_dbschema](https://cloud.githubusercontent.com/assets/26095093/23737659/454872b0-0449-11e7-987d-639b0415dca4.png)
[DbVisualizer_complete.pdf](https://github.com/MIT-LCP/mimic-code/files/829890/DbVisualizer_complete.pdf)
[MIMIC_III_Primary_Key_view_DBVisualizer.pdf](https://github.com/MIT-LCP/mimic-code/files/829889/MIMIC_III_Primary_Key_view_DBVisualizer.pdf)
[Table_Name_DBVisualizer.pdf](https://github.com/MIT-LCP/mimic-code/files/829891/Table_Name_DBVisualizer.pdf)

I've used the foreign keys suggested in buildmimic. Hope these are useful.

**Comment by Ouwen** [comment]
+1

**Comment by alistairewj** [comment]
Looks good. Some noteable omissions:

* icd9_code for diagnosis/procedures should link to
d_icd_diagnoses/d_icd_procedures as appropriate.
* Spec/ab/org itemid in the micro table should join to d_items
* d_cpt can link to cptcodes

I think this schematic is very useful so thanks a lot for making it! If you
can make those updates I'll throw the schema up on the website. Would also
be interesting to hear how you generated it. If it's not too hard of a
process it might be worth splitting the diagram into a dimension table
schematic and a patient table schematic.


On Mar 16, 2017 11:42 AM, "postgres-newbie" <notifications@github.com>
wrote:

Closed #183 <https://github.com/MIT-LCP/mimic-code/issues/183>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MIT-LCP/mimic-code/issues/183#event-1002965641>, or mute
the thread

**Comment by vojtechhuser** [comment]
can you post a link to where in github repo this file lives (for the long run) (if updated).
https://cloud.githubusercontent.com/assets/26095093/23737659/454872b0-0449-11e7-987d-639b0415dca4.png

**Comment by alistairewj** [comment]
Currently hosting something similar here: https://mit-lcp.github.io/mimic-schema-spy/
