### ISSUE TITLE
Change documentation for CPTEVENTS

### ISSUE THREAD

**Issue by postgres-newbie** [MIT-LCP/mimic-code#184]
Link: https://mimic.physionet.org/mimictables/cptevents/

The CPTEVENT.csv table does not have the following columns to link it to 3 tables:
ICUSTAYS on ICUSTAY_ID
D_ITEMS on ITEMID
CAREGIVERS on CGID

Either change the documentation, or if you intended on connecting CPTEVENTS to ICUSTAYS, D_ITEMS and CAREGIVER, please provide the related columns in the .csv file

**Comment by alistairewj** [comment]
The documentation you linked doesn't list those columns for CPTEVENTS: this
is as it should be because they are not present for that table. Where did
you see otherwise?

On Mar 8, 2017 10:57 AM, "postgres-newbie" <notifications@github.com> wrote:

Link: https://mimic.physionet.org/mimictables/cptevents/

The CPTEVENT.csv table does not have the following columns to link it to 3
tables:
ICUSTAYS on ICUSTAY_ID
D_ITEMS on ITEMID
CAREGIVERS on CGID

Either change the documentation, or if you intended on connecting CPTEVENTS
to ICUSTAYS, D_ITEMS and CAREGIVER, please provide the related columns in
the .csv file

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MIT-LCP/mimic-code/issues/184>, or mute the thread

**Comment by postgres-newbie** [comment]
![screen shot 2017-03-08 at 2 47 18 pm](https://cloud.githubusercontent.com/assets/26095093/23727812/71f87cc8-040e-11e7-8ae7-085370b0e154.png)

In the link: https://mimic.physionet.org/mimictables/cptevents/

@alistairewj : You're looking under the "Table columns" section, please see the screen shot showing the section "Links to: " which lists 
ICUSTAYS on ICUSTAY_ID
D_ITEMS on ITEMID
CAREGIVERS on CGID

Please remove this from under "Links to:" because these columns don't exist in CPTEVENTS.

**Comment by tompollard** [comment]
Thanks Krupa, we have updated the documentation as suggested. In case you spot anything else that needs updating, you can submit edits to the page directly by clicking the "Edit this page" link in the left hand menu (e.g. at https://mimic.physionet.org/mimictables/cptevents/).
