### ISSUE TITLE
The time from admission to death.

### ISSUE THREAD

**Issue by zhidehu** [MIT-LCP/mimic-code#185]
I plan to study the prognostic value of some biomarkers, and the endpoint is all-cause mortality. One variable that I must extracted from MIMIC III is the follow-up time (survival time).
The follow-up time can be defined as the period between ADMITTIME and DOD_SNN. If the value of DOD_SNN is null, how can I define the follow-up time (MIMIC III v1.4)? 
According to the guideline of MIMIC III, DOD_SSN (which also contributes to the DOD column) is acquired from the social security death registry, i.e. an external source. It contains dates of death up to 90 days in the future for Metavision patients. It contains dates of death up to 4 years in the future for CareVue patients.
https://mimic.physionet.org/mimicdata/datatypes/
Does this means that for the subjects whose record with null value of DOD_SSN, they have lived more than 4 years after being discharged from hospital?

By the way, what does Metavision and CareVue patients mean?

**Comment by alistairewj** [comment]
I've added some more information on MetaVision and CareVue to the website: https://mimic.physionet.org/mimicdata/metavision/ https://mimic.physionet.org/mimicdata/carevue/

Put simple, they are different ICU database systems which were used at different time periods. They were merged together in MIMIC-III.

A null value for DOD_SSN indicates that we do not have a record of that patient dying ... and so yes, you can assume that they have lived after hospital discharge for some time. The death records were acquired in early 2013. The last patient discharged was in late 2012, so you have at least 90 days of follow up for all patients. Unfortunately due to the de-identification we cannot tell you more than that.

Since CareVue was the system used for earlier patients, you can elect to only use patients from there, in which case you would have a longer follow up time (4 years). This may be useful for your analysis if you need a long post-hospital discharge follow up time.

Side note: if you think the website is lacking clarity in some detail, we welcome issues and, even better, PR which improving on it. Here's the website GitHub: https://github.com/MIT-LCP/mimic-website

**Comment by zhidehu** [comment]
Dear Johnson,
Thank you for your kind reply.
Best wishes.




Zhi-De Hu, MD
Department of Laboratory Medicine, General Hospital of Ji’nan Military Region, Ji’nan, Shandong Province, China. 250031
Researchgate: https://www.researchgate.net/profile/Zhi_De_Hu
Publons: https://publons.com/author/904057/zhi-de-hu#profile
Executive editorofJournal of Laboratory and Precision Medicine
Executive editorofAnnals of Translational Medicine
Section editorofJournal of Thoracic Disease


原始邮件
发件人:Alistair Johnsonnotifications@github.com
收件人:MIT-LCP/mimic-codemimic-code@noreply.github.com
抄送:zhidehuhzdlj81@163.com; Authorauthor@noreply.github.com
发送时间:2017年3月11日(周六) 01:17
主题:Re: [MIT-LCP/mimic-code] The time from admission to death. (#185)


I've added some more information on MetaVision and CareVue to the website: https://mimic.physionet.org/mimicdata/metavision/ https://mimic.physionet.org/mimicdata/carevue/
Put simple, they are different ICU database systems which were used at different time periods. They were merged together in MIMIC-III.
A null value for DOD_SSN indicates that we do not have a record of that patient dying ... and so yes, you can assume that they have lived after hospital discharge for some time. The death records were acquired in early 2013. The last patient discharged was in late 2012, so you have at least 90 days of follow up for all patients. Unfortunately due to the de-identification we cannot tell you more than that.
Since CareVue was the system used for earlier patients, you can elect to only use patients from there, in which case you would have a longer follow up time (4 years). This may be useful for your analysis if you need a long post-hospital discharge follow up time.
Side note: if you think the website is lacking clarity in some detail, we welcome issues and, even better, PR which improving on it. Here's the website GitHub: https://github.com/MIT-LCP/mimic-website

**Comment by zhidehu** [comment]
Dear Johnson,
Thank you for your kind reply.
Best wishes

**Comment by mylanhong** [comment]
Dear Johnson, I have got a question about the mortality. We  can get the hospital mortality from hospital level data since the ADMITTIME and DOD_HOSP can be easily got from ADMISSIONS table and Patiens table respectively. However, how can I get the mortality during ICUstay?

**Comment by alistairewj** [comment]
Indeed you can, if you cross-reference `outtime` in the ICUSTAYS table with the `deathtime` in the ADMISSIONS table - usually with an added "fuzziness" of a few hours to allow for slight misalignment between the times.

**Comment by mylanhong** [comment]
Thank you for your answer  ! @alistairewj
