### ISSUE TITLE
about mortality rate

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#191]
In the PATIENTS table of MIMIC iii, each "SUBJECT_ID" relates to one EXPIRE_FLAG, with "0" representing "survival" and "1" represents "non survival", right? If so, when I link PATIENTS table( containing no "HADM_ID" or "ICUSTAY_ID" column) to LABEVENTS table (containing both"SUBJECT_ID" and "HADM_ID" columns)or CHARTEVENTS table(containing "SUBJECT_ID","HADM_ID" and "ICUSTAY_ID" columns), how can I get one patient's "HADM_ID" and "ICUSTAY_ID" when he was dead(i.e.EXPIRE_FLAG=="1")since a single patient had multiple admissions to the hospital or ICU.
Another question, I want  to study the prognostic value of some serum indicators in LABEVENTS table.When I filter all the subjects(about 8000)that have the serum indicators tested, I found the mortality of these subjects high to 50%(dividing No. of EXPIRE_FLAG==“1” by the total of subjects). Was that reasonable or it was confounded by my misunderstanding of first question?

**Comment by tompollard** [comment]
> In the PATIENTS table of MIMIC iii, each "SUBJECT_ID" relates to one EXPIRE_FLAG, with "0" representing "survival" and "1" represents "non survival", right? 

Correct, 0 means alive and 1 means dead. "The minimum amount of time a patient must survive in order to not have a date of death in the MIMIC-III v1.3 database is 150 days. Most patients are alive for longer: but this is the minimum".

> when I link PATIENTS table( containing no "HADM_ID" or "ICUSTAY_ID" column) to LABEVENTS table (containing both"SUBJECT_ID" and "HADM_ID" columns)or CHARTEVENTS table(containing "SUBJECT_ID","HADM_ID" and "ICUSTAY_ID" columns), how can I get one patient's "HADM_ID" and "ICUSTAY_ID" when he was dead(i.e.EXPIRE_FLAG=="1")since a single patient had multiple admissions to the hospital or ICU.

It isn't appropriate to be using the patients.expire_flag in this case. If your interest is in seeing whether a patient died during a hospital admission, you could look at the hospital_expire_flag in the admissions table. It would be better to calculate the relevant mortality flag using the dod in the patients table (e.g. for 30 day mortality from time of ICU admission, is the dod greater than the ICU intime and less than the intime + 30 days).

> Another question, I want to study the prognostic value of some serum indicators in LABEVENTS table.When I filter all the subjects(about 8000)that have the serum indicators tested, I found the mortality of these subjects high to 50%(dividing No. of EXPIRE_FLAG==“1” by the total of subjects). Was that reasonable or it was confounded by my misunderstanding of first question?

It isn't reasonable to make this assumption, and we would suggest getting a handle on the earlier point before trying to answer a question like this.

**Comment by mylanhong** [comment]
Thank you, Mr Tom Pollard !
