### ISSUE TITLE
Postgres build does not respect Makefile SCHEMA

### ISSUE THREAD

**Issue by tnaumann** [MIT-LCP/mimic-code#195]
The top level Makefile specifies `SCHEMA=mimiciii` which suggests that it can be changed. However, `postgres_create_tables.sql` ignores this configuration and hard codes the schema.

**Comment by tnaumann** [comment]
One possibility for doing this might be to create a temporary schema (e.g., `buildmimic`) when populating the tables which could then subsequently be renamed using something like:

```
psql "$(DBCONN)" -c "ALTER SCHEMA buildmimic RENAME TO $(SCHEMA)"
```

**Comment by alistairewj** [comment]
Thanks - eventually figured out you can set the schema via the command line using the options flag:
https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS  (under "options"). Makefile now creates a single database connect string which includes the schema. It would be nice if you could pass those parameters to the make file rather than manually editing them but this works for now. I tested it locally and it worked - let me know if you have trouble and reopen this!
