### ISSUE TITLE
postgres_load_data.sql throwing error

### ISSUE THREAD

**Issue by EdwardMoseley** [MIT-LCP/mimic-code#202]
Hi all, 

I'm following the tutorial [Installing MIMIC-III in a local Postgres database on Windows](https://mimic.physionet.org/tutorials/install-mimic-locally-windows/) directly, but when I call

`\i postgres_load_data.sql`

I'm getting:

> psql:postgres_load_data.sql:33: ERROR:   relation "admissions" does not exist

Any ideas?

Thanks so much,
Ned

**Comment by alistairewj** [comment]
It looks like the search path for the schema is defined a bit late in the windows instructions, so all the tables are probably on the public schema rather than mimiciii. You can confirm this by running:

```
set search_path to public;
\dt
```

That should spit out a bunch of tables. I would drop all of them (`DROP TABLE ADMISSIONS`, etc), then run:

```
set search_path to mimiciii;
\i postgres_create_tables.sql
\i postgres_load_data.sql
```

That will create all the tables on `mimiciii`, then populate them with data. I'll fix up that guide now.

**Comment by alistairewj** [comment]
Ah, you may need to create the schema first:

```
CREATE SCHEMA mimiciii;
```

**Comment by EdwardMoseley** [comment]
Nailed it. Thanks a bunch Alistair!

**Comment by alistairewj** [comment]
Great glad to hear it - also just updated the tutorial (https://github.com/MIT-LCP/mimic-website/commit/460ffeda51db41b74ecf05783c3914517e49056f) so should be clearer for future users.
