### ISSUE TITLE
CREATE TABLE SCRIPTS NOT RUNNING

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#210]
"PLEASE HELP"
syntax error at or near 
"\set ON_ERROR_STOP 1"

**Comment by alistairewj** [comment]
Could you provide more detail on the error? It's impossible to diagnose this without knowing what operating system you are on, how you are running the code, what program is reporting a syntax error, etc.

**Comment by erjthakur** [comment]
Hello, Thanks for the reply
Actually i am using Windows 7 ultimate (32 bit), after creating database mimic and schema mimiciii i tried to run the script postgres_create_tables.sql but there is this error( SEE ATTACHMENT). I am trying to import data(mimic) into the table but because of this its not happening.  I tried this in Postgres 9.6,Postgres 9.5,Postgres 9.4. But its the same problem every time. 
 When i tried to run the script in PgAdmin (GUI) the error was on \set ON_ERROR_STOP 1 line. Even when i tried to remove it. It was not able to create any table.
(PLEASE SEE ATTACHMENT FOR THE ERROR)
![error](https://cloud.githubusercontent.com/assets/27729999/25777578/9f44b01a-32fe-11e7-8ab2-b050da5a32ec.png)

**Comment by alistairewj** [comment]
I believe you have downloaded the HTML page for the scripts, not the raw
SQL file. When downloading the files through GitHub, you can't right click
and save individual pages - only the "raw" page. We recommend downloading
the entire repository either via git or downloading the zip file:
http://stackoverflow.com/questions/6466945/fastest-way-to-download-a-github-project

**Comment by erjthakur** [comment]
using the sql shell i used the raw file and in PG Admin( GUI) i used the raw and i have also been getting the warning error
console code page (437) differs from windows code page (1252)......

as soon as i enter username and password in sql shell

**Comment by erjthakur** [comment]
In sql shell i used .sql files  and in the pg admin(GUI) i copied the complete script and pasted it in the query builder and executed it. and i have also been getting the warning error
console code page (437) differs from windows code page (1252)......

as soon as i enter username and password in sql shell

**Comment by erjthakur** [comment]
Dear sir
this is what i have been doing
Please see the video attached

**Comment by tompollard** [comment]
As @alistairewj explained in his earlier post, you were trying to load HTML files into your database, not the the SQL scripts. We know this because your error message includes HTML tags like `</td>` and `<span title=0.18399s from github-fe127-cp1-...` etc. You can download the scripts from: https://github.com/MIT-LCP/mimic-code/archive/master.zip

> When i tried to run the script in PgAdmin (GUI) the error was on \set ON_ERROR_STOP 1 line. 

The backslash set command (`\set`) is a PSQL metacommand, so cannot be used in the PgAdmin GUI. If you are going to use the GUI instead of PSQL, then you can simply remove this line from the script before running it.

> using the sql shell i used the raw file and in PG Admin( GUI) i used the raw and i have also been getting the warning error console code page (437) differs from windows code page (1252)......

This is a separate issue relating to the way your system is set up. You should be able to find a solution on stackexchange. e.g. see the following posts: 
- http://stackoverflow.com/questions/20794035/postgresql-warning-console-code-page-437-differs-from-windows-code-page-125 
- https://dba.stackexchange.com/questions/171490/warning-console-code-page-437-differs-from-windows-code-page-1252-8-bit-cha/171491

**Comment by tompollard** [comment]
@erjthakur As there has been no more on this over the past few days, I assume the problem was resolved. If you still need help, please reopen this issue and provide a clear explanation of the steps you are taking to install MIMIC, along with any error messages you receive.

**Comment by erjthakur** [comment]
Yes sir the problem has been resolved and it was a mistake on my part.
THANK YOU FOR ALL THE HELP
