### ISSUE TITLE
Error with postgres_load_data

### ISSUE THREAD

**Issue by ErikWDoty** [MIT-LCP/mimic-code#217]
Greetings!

I am trying to load MIMIC on my windows computer. I followed all the steps, however when I get to the postgres_load_data step I receive the following error:

`psql:postgres_load_data_7zip.sql:33: ERROR:  missing data for column "has_chartevents_data"
CONTEXT:  COPY admissions, line 2: "21,22,165315,2196-04-09 12:26:00,2196-04-10 15:54:00,,"EMERGENCY","EMERGENCY ROOM ADMIT","DISC-TRAN ..."`

I receive the same error regardless of whether I try to load the compressed or uncompressed data/
Any ideas?

**Comment by alistairewj** [comment]
What version of the data have you downloaded? If you're not sure.. do you
know roughly when you downloaded the data? My first guess is you have a
version mismatch.

On May 19, 2017 12:40 AM, "ErikWDoty" <notifications@github.com> wrote:

Greetings!

I am trying to load MIMIC on my windows computer. I followed all the steps,
however when I get to the postgres_load_data step I receive the following
error:

psql:postgres_load_data_7zip.sql:33: ERROR: missing data for column
"has_chartevents_data" CONTEXT: COPY admissions, line 2:
"21,22,165315,2196-04-09 12:26:00,2196-04-10 15:54:00,,"EMERGENCY","EMERGENCY
ROOM ADMIT","DISC-TRAN ..."

I receive the same error regardless of whether I try to load the compressed
or uncompressed data/
Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MIT-LCP/mimic-code/issues/217>, or mute the thread

**Comment by ErikWDoty** [comment]
I just switched to a new computer (Mac to PC) and am trying reload the database. So I just downloaded all the latest data files a few days ago.

**Comment by alistairewj** [comment]
Okay, strange. Roughly, the error is saying that the columns in the admissions table (which was created to hold the data) don't match the columns in the data file. To that end, we should check what columns are in the table and what are in the data file.

For the table: open up PSQL Shell, and type `\d admissions`
For the data file: If you have the proper command line tools, you can do `head ADMISSIONS.csv` - but if you're on PC, it might be easier to just open up the ADMISSIONS.csv file in excel and copy/paste the header line

My alternative guess is that the script is trying to load data into a table on the wrong schema. Roughly the structure of the database is:

mimic
|-> mimic-iii
    |-> admissions
    |-> ...
|-> public

By default postgres tries to insert data into `public`, so if you don't specify the schema (by running the command `set search_path to mimiciii` at the beginning of running PSQL), then it will try to load the data in the wrong place.

**Comment by alistairewj** [comment]
We recently updated the tutorial to emphasize this point!
https://mimic.physionet.org/tutorials/install-mimic-locally-windows/

**Comment by ErikWDoty** [comment]
It was a column mismatch. For some reasons in the create table script I was using, it had an extra column in it. I removed that line and it should be working now

Thanks!
