### ISSUE TITLE
Resolving Conflicting Measurements

### ISSUE THREAD

**Issue by gregory-clemetric** [MIT-LCP/mimic-code#222]
If we consider the measurements that all are lumped together as SBP (as defined here:  https://github.com/MIT-LCP/mimic-code/blob/master/concepts/cookbook/sbp.sql), there are instances where a subject has two different types of measurements from the same charttime.  In some cases, the numbers are very different.  How should we select a single value to use?

**Comment by alistairewj** [comment]
It's possible that the "audit trail" of the measurement is available, so to
speak. Have you checked if the `iserror` column != 1?

**Comment by alistairewj** [comment]
It's possible that the "audit trail" of the measurement is available, so to
speak. Have you checked if the `iserror` column != 1?

On May 26, 2017 3:32 PM, "gregory-clemetric" <notifications@github.com>
wrote:

If we consider the measurements that all are lumped together as SBP (as
defined here: https://github.com/MIT-LCP/mimic-code/blob/master/
concepts/cookbook/sbp.sql), there are instances where a subject has two
different types of measurements from the same charttime. In some cases, the
numbers are very different. How should we select a single value to use?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MIT-LCP/mimic-code/issues/222>, or mute the thread

**Comment by chris20881** [comment]
I had a quick look at these SBP numbers, and as far as I can see the different measurements at the same time relate to invasive measurements (eg itemid 51) and non-invasive measurements (eg itemid 455). This is a recognised issue, and although both techniques aim to measure the same thing, they work in very different ways and have different sources of error etc. I have just been looking for an article on this, and didn't find the one I was thinking of, but actually found one based on mimic ii (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3724452/) that looks interesting (though there are lots of issues).

I am not sure if I could suggest anything useful about which one to use, eg if a patient is hypertensive it is quite possible the IBP will be overreading, but in the same patient if they are hypotensive the IBP may be more accurate, and it would obviously be problematic to swap between the two. If you can avoid SBP and use MAP, you will almost certainly see much greater agreement. Hope this is useful.

Chris

**Comment by gregory-clemetric** [comment]
Thanks!  

After removing the items that were flagged as errors, we decided that the number of times that there was a major discrepancy was small enough that we could use the average of the measurements.  

We are also using MAP.
