### ISSUE TITLE
Issue with psql; concepts; severity scores

### ISSUE THREAD

**Issue by mzhao94** [MIT-LCP/mimic-code#223]
My goal is to extract the 3 severity-scores from MIMIC-III using the scripts provided in the repository. The README for this states that I need to "make concepts" before extracting the severity scores. Every time I try to do this, I have an issue with the psql command. I know that it is installed on the system, but I was wondering if I needed to manually open a server? I'm on a linux system. If not, is there another way to extract the severity scores? 

psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

**Comment by tompollard** [comment]
@mzhao94 psql is a client for connecting to a Postgres database. When you run psql it tries to connect to the database server but in your case it fails, most likely because your database server isn't running. I would suggest googling your error message. Perhaps one of the suggestions at: http://www.revsys.com/writings/postgresql/errors.html might help?

If you normally use a different method for connecting to your copy of the MIMIC database, then just use that method instead. As long as you can run SQL queries on your database, you can create the severity score views and extract the data.
