### ISSUE TITLE
CHARTEVENT.csv file does not open completely

### ISSUE THREAD

**Issue by benbastaki** [MIT-LCP/mimic-code#233]
Hi,

Can you please advise how I can open the chartevent file (excel file) successfully and view complete data. 
It does not open it completely and it says that File is too large.
I would like to use excel file for my work so please suggest a solution\fix.

Regards.

**Comment by tompollard** [comment]
@benbastaki Excel is not particularly well suited to working with the chartevents data, because of the file size and because of the way that Excel handles data types. 

If you are getting an error saying "File too large" then most likely you'll need to use different software. Most of the popular data analysis packages should be suitable. We use Python and R mostly, but alternatives like Matlab, SAS, etc should also be fine.

**Comment by benbastaki** [comment]
@tompollard  do you mean I can use csv files in matlab and chartevents will be open completly?

I tried to read the chartevents in matlab but I get a message = memory low . I have 17 GB memory on the pc! 
I dont get mimic code respository how it works. It seems most of codes are wrriten for Linux environment

**Comment by tompollard** [comment]
@benbastaki the chartevents table is ~33GB, so is too big to fit into your RAM. My suggestion would to first load the data into a database system such as Postgres (see the tutorial at: https://mimic.physionet.org/tutorials/install-mimic-locally-windows/). You can then extract a reduced dataset for your analysis using SQL.

For a simple example that combines an SQL query with analysis in Python, see: https://github.com/MIT-LCP/mimic-code/blob/master/notebooks/first_labs.ipynb. Postgres and Python are both supported by Windows, so this code should be reproducible on your machine.

**Comment by benbastaki** [comment]
@tompollard  Thanks for your help, I really appreciate it. Just to double check, so will I be able to use tables created in postgres(i am assuming postgres files will have sql extension?!) in Matlab ? Is there any code\script that it is used postgres in matlab?

Do you know what is the size of MIMIC database in postgres?

Thanks,
Ben

**Comment by alistairewj** [comment]
There is very preliminary MATLAB code here:
https://github.com/MIT-LCP/mimic-workshop/blob/master/mlcc/lab1-data-extraction/mlcc1_introduction.m

That uses SQLite instead of PostgreSQL - but it does give you a hint on
what MATLAB functions you should read up about. Essentially, you need the
database installed with all the data. Then, you can run an .sql file via
MATLAB, and have the result returned directly into MATLAB. In order to do
this (off the top of my head), you'll need to install the database system,
find the appropriate driver (the .jar file), and then tinker with the code
a bit.

If you figure out how to do this we'd love a tutorial which we could add
the repository - I think a lot of MATLAB users would appreciate the lessons
you learn along the way.

**Comment by manashty** [comment]
@benbastaki 
I suggest that you load the database to a local PostgreSQL database. The size with index is around 79GB. I think the database itself is around 40GB.

Postgres is the best tool to query this dataset. Chartevent alone does not help you much as you will probably need a lot of joins with other tables and that means a DBMS is the best way (if not the only) to do it.
