### ISSUE TITLE
47 diagnoses_icd.sequence are null. Why?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [MIT-LCP/mimic-code#24]
I see 47 diagnoses_icd.hadm_id are null:

``` sql
SELECT count(*) FROM  mimiciii.diagnoses_icd  WHERE diagnoses_icd.seq_num is null;
```

Bug or intended?

**Comment by tompollard** [comment]
> Bug or intended?

Depends on your perspective! The null entries appear in the raw hospital data. 

We try to provide a true representation of the underlying data and generally err on the side of too little cleaning rather than too much, so the rows were not removed during the process of building MIMIC. 

We could remove them in the future. I'll make a note to consider this for the next release.
