### ISSUE TITLE
Why labs-first-day.sql filter data by past 6 hours and future 1 day

### ISSUE THREAD

**Issue by yun-li** [MIT-LCP/mimic-code#245]
For the code mimic-code/concepts/firstday/labs-first-day.sql on line 121

`le.charttime BETWEEN (ie.intime - interval '6' hour) AND (ie.intime + interval '1' day)`

This should be data in the first 24 hours of ICU admission, why we include data before 6 hours of the ICU admission?

**Comment by alistairewj** [comment]
Personal choice on my part - labs are often collected in the emergency department slightly before ICU admission. Since the ICU `intime` is administratively defined, i.e. it is not related to physical ICU admission and consequently will be a noisy estimate of true ICU admission time, I added a fuzzy window for the labs. It's also because the labs are one of the few data elements available outside the ICU.
