### ISSUE TITLE
Abnormal flag threshold for LABEVENTS?

### ISSUE THREAD

**Issue by Bowiemb** [MIT-LCP/mimic-code#250]
Does anyone know where I can find the threshold limits for abnormal/normal flags for the LABEVENTS?

I've checked here- https://mimic.physionet.org/mimictables/labevents/ - but it doesn't provide details. 

Thank you. 

My best,
Michael 

EDIT- I can approximate them, but I wasn't sure if they were listed somewhere.

**Comment by alistairewj** [comment]
Unfortunately these are not available in the database as is. You may want to look into linking these to the LOINC data via the LOINC code which should contain a reference range. You can download the LOINC information for free from: https://loinc.org/

**Comment by Bowiemb** [comment]
@alistairewj What do you mean by "these are not available"? The "abnormal" flag is a part of the dataset. It is underneath the "FLAG" column in the LABEVENTS file. I was trying to find how MIMIC flagged these.

**Comment by tompollard** [comment]
Hi Michael, thanks for your messages.

> @alistairewj What do you mean by "these are not available"?

By "not available", Alistair means that we are unable to provide the threshold limits for abnormal/normal flags for the MIMIC-III `labevents` table because the information is not in our possession.

> The "abnormal" flag is a part of the dataset. It is underneath the "FLAG" column in the LABEVENTS file.  I was trying to find how MIMIC flagged these.

When creating MIMIC, we do not derive details such as abnormal flags ourselves. MIMIC is a representation of the underlying data provided by multiple sources across the hospital. The flag appears in this data. 

Abnormal flags are included in the `labevents` table, as you note. The flags are recorded when comparing lab values against threshold ranges. The threshold ranges are not static, may vary based on reagents, and unfortunately are not known to us at present.

**Comment by Bowiemb** [comment]
@tompollard Ah, that makes sense. Thank you so much for your explanation.

**Comment by tompollard** [comment]
Thanks @Bowiemb, glad this helped.
