### ISSUE TITLE
Mixture of Materialized Views / Tables In concepts

### ISSUE THREAD

**Issue by jraffa** [MIT-LCP/mimic-code#254]
In at least two of the concepts:

`crrtdurations` and `ventdurations` 

the end result is a **table**, while the others produce **materialized views**.  Just wondering if this is intended behaviour, or the result of some legacy code.

**Comment by tompollard** [comment]
I don't think this difference is intentional, so switching to a materialized view makes sense for consistency.

Tables and materialized views are pretty similar in Postgres...the main difference is that the query used to create a materialized view is retained, so the view can be regenerated with `REFRESH MATERIALIZED VIEW`. 

Materialized views apparently [don't support "automatic generation of OIDs"](https://www.postgresql.org/docs/current/static/sql-creatematerializedview.html), which are [object identifiers](https://www.postgresql.org/docs/9.5/static/datatype-oid.html) assigned to rows. These are turned off by default for user generated tables anyway, so this doesn't seem to matter.

**Comment by alistairewj** [comment]
Yeah little bit of inconsistency that's best fixed! Thanks @tompollard !
