### ISSUE TITLE
neonates gestational age

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#255]
can you please provide us the postgresql query to extract gestational age of neonates from noteevents (text) who had a blood culture.
Or any such examples where data has been extracted from text column of noteevents or it has to be done manually one by one?

Thanks in advance.

**Comment by tompollard** [comment]
@erjthakur We do our best to help answer questions about MIMIC, but we don't have the capacity to carry out research projects for other groups. I'll close this issue for now, but it would be great if you could post an update when you have surveyed the literature and attempted your query, so that others can benefit from this work too.
