### ISSUE TITLE
ventilator mode recordings with unknown value

### ISSUE THREAD

**Issue by ayoung01** [MIT-LCP/mimic-code#26]
In CHARTEVENTS, there are 5484 ventilator mode recordings (ITEMID in (720, 223849)) that have blank values and another 7709 recordings that have uninformative values ("Other/Remarks")

**Comment by alistairewj** [comment]
This will happen for many values. "Other/Remarks" indicates that the staff have made a comment in the `COMMENTS` field for that value. However, due to PHI concerns, we have not included the `COMMENTS` column in the release. The other NULL values may also be comments, or they may contain data in one of the other columns (`RESULTSTATUS` or `STOPPED`).

**Comment by alistairewj** [comment]
Closing this issue - let us know if you have extended concerns.
