### ISSUE TITLE
Travis CI build broken for postgres build

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/mimic-code#266]
Can't seem to build the dataset with the test scripts.. I updated them for v1_4, but I doubt it's fixed it. Here's the stack trace (unrelated to the actual pull request): https://travis-ci.org/MIT-LCP/mimic-code/builds/260484226?utm_source=github_status&utm_medium=notification

Seems related to using `\set ON_ERROR_STOP 1` - I think we can't use psql commands like `\set` in this script but not sure - any ideas @tompollard ?

**Comment by tompollard** [comment]
Tests were fixed in https://github.com/MIT-LCP/mimic-code/commit/75e30ab4ac83ed19907938053b77e8f14f185182

New methods can be added to the following script:
https://github.com/MIT-LCP/mimic-code/blob/master/tests/test_postgres_build.py

All tests are run against a copy of the [MIMIC demo database](https://mimic.physionet.org/gettingstarted/demo/).

An example test is: 
```python
    def test_SELECT_min_subject_id(self):
        """
        Minimum subject_id in the demo is 10006
        """
        test_query = """
        SELECT min(subject_id) 
        FROM {}.patients;
        """.format(self.db['schema'])

        min_id = pd.read_sql_query(test_query,self.con)
        self.assertEqual(min_id.values[0][0],10006)
```
