### ISSUE TITLE
How to build MIMIC-III database in MySQL?

### ISSUE THREAD

**Issue by noalnak** [MIT-LCP/mimic-code#283]
I saw some sql scripts under MySQL but it provides instructions to use csv2mysql, I need help where to get this application. Thanks in advance.

-Gerald

**Comment by tompollard** [comment]
This seems to relate to the comment in: https://github.com/MIT-LCP/mimic-code/blob/master/buildmimic/mysql/1-define.sql

```
-- csv2mysql with arguments:
--   -o
--   1-define.sql
--   -u
--   -k
--   -p
--   -z
```

**Comment by noalnak** [comment]
yes tom. would you know where can I get the csv2mysql code to run it with the arguments specified? 

Or, would you know how can I build MIMIC-III database in MySQL? Please advise.

thank you.

**Comment by alistairewj** [comment]
Hi @noalnak - the csv2mysql tool is provided by @pszolovits and was used to generate the scripts for table generation and data loading. You don't need it to load the data itself - you should be able to just run the scripts in the repository as they are to create the tables and load the data.

For reference, you can find the tool here: https://github.com/mit-medg/csv2mysql

Also, as an aside, we would recommend using PostgreSQL instead of MySQL. The scripts in this repository are written to work with postgres and you'll likely run into many errors trying them in MySQL (for example, the `with` clause isn't supported by MySQL so any query with a `with` clause will need to be rewritten). Of course it's completely up to you!

**Comment by noalnak** [comment]
Thank you Alistair.

**Comment by pszolovits** [comment]
I created csv2mysql, and thought I had posted it. I'm traveling this week but will check on this when I return. 

Peter Szolovits ~ iPhone
