### ISSUE TITLE
KDIGO criteria for AKI

### ISSUE THREAD

**Issue by yun-li** [MIT-LCP/mimic-code#294]
Hello, 

Thanks for the newly added code for AKI diagnosis. 

According to  http://emedicine.medscape.com/article/1925597-overview#a4
KDIGO defines AKI as any of the following:
1. Increase in serum creatinine by 0.3mg/dL or more within 48 hours or
2. Increase in serum creatinine to 1.5 times baseline or more within the last 7 days or
3. Urine output less than 0.5 mL/kg/h for 6 hours

As for the third criteria, **Urine output less than 0.5 mL/kg/h for 6 hours**, the unit is **mL/kg/h**
However, it seems that according to the newly added code https://github.com/MIT-LCP/mimic-code/blob/master/concepts/organfailure/kdigo-admission.sql 
the unit of urine output is mL/kg. Is this a mistake? Correct me if I am wrong.

Thanks very much,
Yun

**Comment by alistairewj** [comment]
You're right! Good catch. I've just fixed it in the above commit. I'll also take this opportunity to change the output columns for the query since I think the `aki` column is a bit ambiguous.

**Comment by yun-li** [comment]
Thanks very much for your prompt reply. 

According to the criteria, **Urine output less than 0.5 mL/kg/h for 6 hours**, my understanding is that it requires urine output to be less than 0.5 mL/kg/h for 6 hours continuously; however, the code calculates an average. Is that a discrepancy?

Also, I have a hard time understanding urnieoutput, there is a urine measurement every one or two hours, and the unit is ml. Is this a measurement of the total urine output within the time range from the last measurement until the current measurement? If it is, do you know the reason why the time intervals between two adjacent are different (1h or 2 h)?

Thanks,
Yun

**Comment by alistairewj** [comment]
It would be great to get your opinion on some of the implementation details.

The challenge is there is no way to enforce the rate as they request. The only data regarding UO that is documented is the amount, e.g. 50 mL at 14:00. As such the code follows this logic:

1. Sum all UO measurements in a 6 hour period for every possible 6 hour period
2. Convert these summations into a rate (mL/kg/hour) - I suppose this is the average rate over the 6 hours
3. Calculate the minimum rate over the first 48 hours
4. If the minimum rate is less than the criteria, classify the patient as having AKI

If the patient's minimum UO was always higher than 0.5 mL/kg/hour, then If the patient has no urine output measurements in the first 48 hours, all the stagings/classification will be null.  I'm not really sure how you could implement this without calculating the average rate over 6 hours - thoughts?

The time intervals vary because UO is documented aperiodically - so if there is a time interval of 2 hour between two measurements, the documented value probably corresponds to the last 2 hours.

There are a few things about the implementation that would be good to discuss:

1. Right now the 7-day criteria use urine output from the first 48 hours - I'm a bit unsure whether it should be using urine output from the full 7 days.
2. The admission creatinine is the first creatinine value up to 6 hours before ICU admission and up to 24 hours after ICU admission. For some patients we have creatinine values earlier than this - not sure what the best choice of "baseline" is, particularly as some patients may be admitted to the ICU in ARF.

**Comment by alistairewj** [comment]
Just refactored a bit - reworked the column names to be clearer and defined the AKI staging in a subquery so that we don't end up with multiple blocks of code doing the same thing.

As a side note, the code will need to incorporate initiation of RRT in order to really replicate the KDIGO criteria.

**Comment by yun-li** [comment]
Hi,

Thanks very much for your reply. Here are my thoughts:

1. If the urine output value is the total urine from the last measurement until the current one, then we can calculate the urine output rate by making an average in this small time interval. Then we look for 6 continuous hours where all rate is smaller than 0.5. This might be more accurate than averaging over 6 hours.

2. As for the baseline of the creatinine, my understanding is to use each creatinine measurement as a starting point, and then look for the minimum value in the previous 7 days of the starting point, using that minimum value as the baseline. That's to say, I want to know the maximum possible increase of the creatinine in any 7 continuous days.

Those logistic may be too complex for SQL. Probably we need to use other languages such as Python to achieve the logic after we get the row creatinine or urine data with SQL.

Thanks,
Yun

**Comment by alistairewj** [comment]
You underestimate the expressiveness of SQL! :)

I've spoken with a nephrologist to get some insight and have made some changes to the code base. First, to respond to your points.

1. While in principle this is possible, the practicalities of the data recording prohibit this. Since most data collection for urine output is manual, the data as it stands will not be available exactly every hour. As a result, the time period between two successive measurements would be variable, and most importantly, this variation is likely independent of the patient's physiology (and more determined by staffing factors, time of day, etc). By defining periods of 6 hours, 12 hours, and 24 hours, I believe the KDIGO definition has already specified the level of quantization for the data, and that the rate should be calculated as an average over this time period.
2. In discussions we ended up agreeing that the minimum creatinine is likely a better approximation to "baseline" than the first creatinine - and so I have updated the code to use the minimum during the first 48 or 7 days, as appropriate. However, we did not allow the time window to extend before ICU admission. This was intentional as it makes the definition more comparable to the literature, as most studies only have data available from the ICU. Of course it's easy to remove this restriction - might be worth some sensitivity analysis in any study performed using these definitions.

Also, I refactored the code so that the 48 hour and 7 day calculation are done separately in separate queries. I felt this was clearer (though it does duplicate some code).

I look forward to your thoughts!
