### ISSUE TITLE
some patients miss data

### ISSUE THREAD

**Issue by will4906** [MIT-LCP/mimic-code#301]
Hello, I have runed code blood-gas-first-day-arterial.sql to get the blood gas data, but some of them is null.And I also search them in the labevents, either.
Like hadm_id = 181422.I can't get any data from the labevents where hadm_id = 181422. Is it mean that the nurse did't record the infomation of the patient?Or 
any other situation?

**Comment by alistairewj** [comment]
As you guessed, it means there was no data for that `hadm_id`. The most common explanation is that the data does not exist - but I think you found an edge case where due to some issue in the raw hospital data the `hadm_id` was not assigned to the data for that patient. I can see this because the `subject_id` for that patient (80361) has data. I've written this down so we're aware of it for the next MIMIC update.

Just for your sanity, if you check the labevents table..

```
select 
  count(adm.hadm_id) as num_obs_in_hosp
  , count(le.hadm_id) as num_obs_with_hadm_id
  , count(le.hadm_id)::numeric*100/count(adm.hadm_id) as percent_obs_assigned_hadm_id
from admissions adm
left join labevents le
on adm.subject_id = le.subject_id
and le.charttime between adm.admittime and adm.dischtime;
```

 num_obs_in_hosp | num_obs_with_hadm_id | percent_obs_assigned_hadm_id         
----------------- | ----------------- | ---------------------
20512804 |        20492463 | 99.9008375451742239

You managed to find the 0.1%! :)
