### ISSUE TITLE
The Red Blood C(3.6-6.2) unitname is null

### ISSUE THREAD

**Issue by will4906** [MIT-LCP/mimic-code#321]
Hello, I want to get the value of the Red Blood C(3.6-6.2) whose itemid is 3799. But the the unitname is null, Because I don't know the rules of the hospital. Can someone tell what the unit of the Red Blood C(3.6-6.2) from chartevents.

Thanks very much

**Comment by alistairewj** [comment]
Since the labevents table "feeds" data into the ICU, which eventually ends up in chartevents, we recommend you use the labevents table for lab data.

I took a look at the units and as they are between 3-8, which means they are likely millions of cells per microlitre (m/uL). That's the same unit that is explicitly stated in labevents e.g. itemid 51279.
