### ISSUE TITLE
CRRT durations

### ISSUE THREAD

**Issue by alexandreliborio** [MIT-LCP/mimic-code#323]
Dear, in crrtdurations query, is it really only CONTINUOUS renal replacement therapy? or any hemodialysis procedure? I could not identify no expression. in query that differentiates CRRT of intermitente hemodialysis. If the query is about any RRT, why tis there only 1,054 diferente ICUSTAY_ID in table? How can I identify all RRT procedures performed (including CRRT and intermitente hemodialysis, but NO peritoneal dialysis)?
Very best

**Comment by alistairewj** [comment]
It does not contain information on intermittent hemodialysis. It is only CRRT. The `itemid` are chosen because they are only documented for CRRT.

There are other queries (e.g. RRT) which attempt to identify intermittent dialysis as well - though because of infrequent documentation these estimates are noisier.
