### ISSUE TITLE
Some quetions about LABEVENTS

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#333]
Hi, I want to extract iron parameter in LABEVEBTS. I am wondering how often was the iron measured for the patients? What kind of patients need iron or ferritin measured because I have found not all patients have iron parameters measured.
To perform a survival analysis, I'm wondering how the patients were followed over a 4 year period and how the outcome of 4 year were collected? Were they routinely followed ?
In addition, is hepcidin measured for patients? Hepcidin is an important iron parameter but I cannot found it in MIMIC III.
Thank you very much!

**Comment by tompollard** [comment]
> To perform a survival analysis, I'm wondering how the patients were followed over a 4 year period and how the outcome of 4 year were collected? Were they routinely followed ?

@mylanhong we suggest you read the MIMIC-III documentation and publication, which should answer this question. Essentially the data is collected during the hospital stay and linked to social security data for out of hospital mortality.

> I want to extract iron parameter in LABEVEBTS. I am wondering how often was the iron measured for the patients? What kind of patients need iron or ferritin measured because I have found not all patients have iron parameters measured. is hepcidin measured for patients?

Please begin researching these questions, posting your approach and what you find. Post queries/code/plots so that the community can give feedback. We don't have the capacity to carry out the work on your behalf unfortunately.
