### ISSUE TITLE
icd9_codes in the DIAGNOSES_ICD table must be handled as strings

### ISSUE THREAD

**Issue by Palrandro** [MIT-LCP/mimic-code#337]
The files  DIAGNOSES_ICD.csv and D_ICD_DIAGNOSES.csv are downloaded from https://physionet.org/works/MIMICIIIClinicalDatabase/files/. The problems as follows:
1.In the ICD9 code in the D_ICD_DIAGNOSES.csv file, both 042 and 0042 are shown as 42, indistinguishable, and the corresponding problem is also present in DIAGNOSES_ICD.csv.
2.There are 414 (row1059) and 41400 (row1438) icd9 code in DIAGNOSES_ICD.csv, but no 414 icd9 code in DIAGNOSES_ICD.csv, Are these two encodings the same?
Can you help me?

**Comment by tompollard** [comment]
Hi @Palrandro

> 1.In the ICD9 code in the D_ICD_DIAGNOSES.csv file, both 042 and 0042 are shown as 42, indistinguishable, and the corresponding problem is also present in DIAGNOSES_ICD.csv.

I just downloaded the `D_ICD_DIAGNOSES.csv` file and ran the following command:

```
cat D_ICD_DIAGNOSES.csv | grep 042 | head -n 10
```

...which returns several rows, including the following two:

```
253,"0042","Shigella boydii","Shigella boydii"
513,"042","Human immuno virus dis","Human immunodeficiency virus [HIV] disease"
```

So the file seems fine. Perhaps you are viewing the `icd9_code` column as a numerical field, rather than a string?

> 2.There are 414 (row1059) and 41400 (row1438) icd9 code in DIAGNOSES_ICD.csv, but no 414 icd9 code in DIAGNOSES_ICD.csv, Are these two encodings the same? Can you help me?

Row 1059 of DIAGNOSES_ICD.csv has an icd9_code of `0414 `, not `414  `. We can check this by viewing the CSV file:

```
 sed -n '1059p' DIAGNOSES_ICD.csv
> 450,59,104130,5,"0414"
```

ICD-9 041.4 is a non-billable group code for "_Escherichia coli [e. coli] infection in conditions classified elsewhere and of unspecified site_" (see: https://icd.codes/icd9cm/0414). Several billable subcategories for this code appear in the dictionary:

```
    498 | 04141     | Shiga txn-produce E.coli | Shiga toxin-producing Escherichia coli [E. coli] (STEC) O157
    499 | 04142     | Shga txn prod E.coli NEC | Other specified Shiga toxin-producing Escherichia coli [E. coli] (STEC)
    500 | 04143     | Shga txn prod E.coli NOS | Shiga toxin-producing Escherichia coli [E. coli] (STEC), unspecified
    501 | 04149     | E.coli infection NEC/NOS | Other and unspecified Escherichia coli [E. coli]
```

It is true that the group code 041.4 does not appear in the dictionary. One possibility is that the dictionary does not include non-billable codes. If you would like to look into this issue further, the dictionary was obtained from: https://www.cms.gov/Medicare/Coding/ICD9ProviderDiagnosticCodes/codes.html. 

ICD-9 code `41400` is the code for "_Coronary atherosclerosis of unspecified type of vessel, native or graft_", so it is not at all the same as code `0414 `.

```
sed -n '1438p' DIAGNOSES_ICD.csv 
2972,246,197430,11,"41400"
```

```
mimic=# select * from d_icd_diagnoses where icd9_code like '41400';
 row_id | icd9_code |       short_title        |                               long_title                                
--------+-----------+--------------------------+-------------------------------------------------------------------------
   4373 | 41400     | Cor ath unsp vsl ntv/gft | Coronary atherosclerosis of unspecified type of vessel, native or graft
```
