### ISSUE TITLE
About code status

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#352]
Hello, acoding to mimic code on code_status, we can extracts:
--    i) a patient's first code status
--    ii) a patient's last code status
--    iii) the time of the first entry of DNR or CMO
 what are the 'first' and 'second' mean ? First day after admission to ICU? Last day during the ICU stays?

**Comment by alistairewj** [comment]
The choices of code status were a convenience: the "first" code status is
the first code status that was charted for the  patient in the ICU.
Similarly, the "last" code status is the last one charted. If you make the
assumption that most patients don't have oscillating code status, then you
can get an idea of what proportion of full code patients (on admission)
were made DNR, DNI, CMO, etc.

The first and last aren't fixed to any time window. They are the first and
last charted for the entire ICU stay.

On Dec 18, 2017 9:59 PM, "mylanhong" <notifications@github.com> wrote:

Hello, acoding to mimic code on code_status, we can extracts:
-- i) a patient's first code status
-- ii) a patient's last code status
-- iii) the time of the first entry of DNR or CMO
what are the 'first' and 'second' mean ? First day after admission to ICU?
Last day during the ICU stays?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MIT-LCP/mimic-code/issues/352>, or mute the thread
