### ISSUE TITLE
Rise in vanco level between labs

### ISSUE THREAD

**Issue by lmockus** [MIT-LCP/mimic-code#367]
There are 500+ instances when vanco levels rise from lab to lab with no vanco administration record in inputevents_mv. I am using the query in https://github.com/MIT-LCP/mimic-code/blob/dedd0faed8273748f0db6034088713d62f226305/notebooks/vancomycin-dosing.ipynb. Some examples are:

SUBJECT_ID, HADM_ID, SOURCE, LABEL, CHARTTIME, ENDTIME, VALUE, VALUEUOM
188, 132401, lab, Vancomycin, 2161-11-04 06:50:00, , **0.0**, 0.0, 
188, 132401, lab, Vancomycin, 2161-11-05 04:05:00, , 14.8, 14.8, 
and
99865, 189346, lab, Vancomycin, 2184-12-26 20:31:00, , 18.8, 18.8, 
99865, 189346, lab, Vancomycin, 2184-12-28 21:34:00, , **27.0**, 27, 

I looked into labevents table using the query below and both entries in bold (0ug/mL and 27ug/mL are flagged as abnormal). Does it mean that those entries are considered erroneous and should be ignored or those are good measurements but flagged as abnormally high/low?
select le.* from LABEVENTS as le
inner join D_LABITEMS di on
(le.itemid = di.itemid)
inner join VANCO_ADMIN_SUBJ as vas on
(le.subject_id=vas.subject_id)
where le.SUBJECT_ID=99865 and di.itemid = 51009;

L

**Comment by alistairewj** [comment]
Abnormal means the lab is considered abnormally high or low. It does not mean it is erroneous.

**Comment by lmockus** [comment]
Thanks. It implies that some 500 dose administrations are not recorded in inputevents_mv. Is this possible?

L

**Comment by lmockus** [comment]
Another comment. When fitting the vanco data to one compartmental model I found some strange predictions. By drilling down it became quite obvious that some administrations are missing. By using the query you have developed in https://github.com/MIT-LCP/mimic-code/blob/dedd0faed8273748f0db6034088713d62f226305/notebooks/vancomycin-dosing.ipynb:

SUBJECT_ID, HADM_ID, SOURCE, LABEL, CHARTTIME, ENDTIME, VALUE, VALUEUOM, 
40310, 186361, lab, Vancomycin, 2144-08-06 07:42:00, , 9.7, **9.7**, , 
40310, 186361, poe, Vancomycin, 2144-09-04 00:00:00, 2144-09-28 00:00:00, IV, 1000, , 
40310, 186361, poe, Vancomycin, 2144-10-19 00:00:00, 2144-10-24 00:00:00, IV, 1000, , 
40310, 186361, lab, Vancomycin, 2144-10-20 18:17:00, , 3.6, **3.6**, , 

The level even after 2 months came down from 9.7 to 3.6. There is indication that there was at least one administration based on prescription on 10-19.

Could you suggest any insight how to detect those missing vanco administrations.

L

**Comment by tompollard** [comment]
> It implies that some 500 dose administrations are not recorded in inputevents_mv. Is this possible?

Yes, it is possible that some doses are not captured in the `inputevents_mv` table. There are several possible explanations , but a key point that seems to have been missed in the examples above is `inputevents_mv` does not record events outside the ICU. 

e.g. Cross referencing the first example with the transfers table (`SELECT * FROM transfers WHERE subject_id = 188`), the patient was not admitted to the ICU for this particular hospital stay until `2161-12-17`. 

As he/she was not in the ICU during the period that you are looking at (`2161-11-04` - `2161-11-05`), we would not expect the medication event to be captured in `inputevents_mv`. Perhaps the vancomycin was administered during surgery? 

It seems to be a similar case for `subject_id = 40310`. It is possible that the patient received uncharted vancomycin doses between the lab measurements on `2144-08-06` and `2144-10-20` because the patient was not in the ICU for much of this period.

From a quick glance at `subject_id = 189346` the reason is less clear, but if you or anyone else chooses to explore in more detail we would welcome additional notes here.

> Could you suggest any insight how to detect those missing vanco administrations.

Not currently, although we may supplement MIMIC with non-ICU data in the future.

**Comment by lmockus** [comment]
Thanks a lot. I guess I understood entry admit in transfer table wrong. It means admission to the hospital, correct?

L

**Comment by tompollard** [comment]
> I guess I understood entry admit in transfer table wrong. It means admission to the hospital, correct?

Yes, that's correct.

**Comment by chris20881** [comment]
Sorry, a little late, but this article might be of interest here:
"Unexplained increases in serum vancomycin concentration in a morbidly obese patient"
http://www.intensivecriticalcarenursing.com/article/S0964-3397(16)30066-0/fulltext
Chris

**Comment by lmockus** [comment]
Chris,

Thanks a lot.

L
