### ISSUE TITLE
Some questons about extracting information from discharge summary

### ISSUE THREAD

**Issue by yixuenaqi** [MIT-LCP/mimic-code#378]
Thanks.I want to extract medications on admission in the discharge summary but some patients just take 'Medications' for short.If I use the codes like 'substring(ne.text, 'Medications:(.*?)\n\n') as medic1',I would extract 'Discharge Medications' not 'Medications'.But I want to extract 'Medications',How can I solve this problem?Thank you!

**Comment by alistairewj** [comment]
You'll need to build a few different regexes to extract that info properly. We don't have readily available code for this exact problem, though we always welcome PRs! Otherwise, this is a similar problem to the one tackled by @mghassem and @tompollard : https://github.com/mghassem/medicationCategories
