### ISSUE TITLE
How to find height measurements on carevue

### ISSUE THREAD

**Issue by EmmaRocheteau** [MIT-LCP/mimic-code#394]
I'm struggling to find the height data for carevue. I searched for itemids to do with height:

mimic=> select label, itemid from d_items where lower(label) like '%height%';
     label     | itemid 
---------------+--------
 Height of Bed |    216
 Height Inches |   1394
 Height        | 226707
 Height (cm)   | 226730
(4 rows)

I looked at how many measurements there were for each of these entries:

mimic=> select count(ce.itemid) from chartevents as ce where ce.itemid = 226707; -- Height
 count 
-------
 12015
(1 row)

mimic=> select count(ce.itemid) from chartevents as ce where ce.itemid = 226730; -- Height (cm)
 count 
-------
 12015
(1 row)

mimic=> select count(ce.itemid) from chartevents as ce where ce.itemid = 1394; -- Height Inches
 count 
-------
    26
(1 row)

I was wondering if anyone knew how to get these measurements as I can't do my study without them. Even the counts for metavision appear small, it looks like it hasn't been recorded for most patients. It seems odd given that you need to know the height of the patient to work out what the correct tidal volume should be for that patient.

I'd be grateful for any help!

Emma

**Comment by alistairewj** [comment]
The issue here is that heights are present in a different database system, and the only reason to input the height into MetaVision is if dosing according to body surface area is required. As a result, there aren't too many heights available in MIMIC. For now, the only solution is to deal with the missing data in some way. We hope to improve the completion of this data in a future release.
