### ISSUE TITLE
Baseline vitals

### ISSUE THREAD

**Issue by natny** [MIT-LCP/mimic-code#398]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description
Two questions: 

1. What does a value of 'Done' in chartevents indicate?

2. How does one get the baseline vitals of a patient?

### Steps to Reproduce

1. In postgres: 
select * from chartevents where lower(value) like '%done%' limit 10

**Expected behavior:** [What you expect to happen]
na
**Actual behavior:** [What actually happens]
na
### Additional Information
none
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by alistairewj** [comment]
1. As it stands, "DONE" means a lot of things. Your query doesn't isolate to any individual data element, so the phrase "DONE" corresponds to a lot of different things. You need to filter your queries by `itemid` in order to isolate a single data element. So for example I can do: `select * from chartevents where itemid = 72 limit 10`, where `itemid` 72 is "Back care", and in this case it means that the care team are documenting providing care for the patient's back.
2. Really depends on what you define as baseline - whether on ICU admission, or earlier. To give you some degree of an answer, we only have vital signs while the patient is in the ICU.
