### ISSUE TITLE
Antibiotics Prevalence in MV > CV?

### ISSUE THREAD

**Issue by geickelb** [MIT-LCP/mimic-code#418]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description

I’m working with a group that is conducting research on antibiotic usage, microbiology culture results and outcomes within the first week of presentation in the MIMIC III dataset.

 Using the methodology outlined below, we found more patients in MV >CV that met our study criteria (received antibiotics, had a sterile culture, >16YO) (see table below). Interestingly, the number of patients we found in CV who had antibiotics prescribed was cut in half after we filtered for age and having a sterile culture, while the same trend does not appear to be present in MV. These numbers raised a flag for us because intuitively it seems like we should have more patients from CV. 

| prefiltered N | filtered* N |          Desc         |
|     14261     |    7346    |      CV patients      |
|     11901     |    9958    |       MV patients     |
|      N/A      |   13713    | combined patient list |
*filtered refers to filtering for only patients who have a sterile culture (blood, joint, urine, csf, pleural, spinal, peritoneal, etc...) and who are over the age of 16. 

**The questions I am trying to answer:**

 1.Why are the CV patients who are prescribed antibiotics skewed towards being neonates or not having a sterile culture?
Is the MICROBIOLOGYEVENTS table is skewed towards MV patients? 
Do CV patients have more neonates in their population than MV (see distribution of mimic age attached)?

 2.What does the distribution of antibiotics prescriptions look like overtime in cv & mv?
Due to the de-identified dates, we are unable to perform this analysis ourselves. I have attached a list of item id’s that correspond to what we believe represent the bulk of antibiotics prescribed in the database, can you investigate the distribution of their prescriptions over time in the CV and MV populations? 

antibiotic item id's:
[ab_id's.txt](https://github.com/MIT-LCP/mimic-code/files/1872757/ab_id.s.txt)

distribution of patient age in MIMIC III. (notice the large # of neonates):
![mimic age distribution](https://user-images.githubusercontent.com/18537438/38268105-e79561ae-3742-11e8-8c94-4e56859eaa2c.png)

A brief description of how we arrived at antibiotic item id’s:

First, we cross-referenced the NDC column in PRESCRIPTIONS to get RXCUI and ATC for each drug in PRESCRIPTIONS. Next, we used a combination of rule-based and regular expressions to extract the base names and abbreviations of the antibiotics. Using this list, we queried the D_ITEM labels for any labels that contained the antibiotic names or abbreviations and extracted the associated ITEMID. This list of ITEMIDs was then combined with the ITEMIDs present in the microbiology table. This final list was manually curated to ensure only anti-bacterial were present.

**Comment by alistairewj** [comment]
Thanks for the thorough analysis when posting this issue! Happily this is something we've looked at so I think I can clear up most of your confusion.

### Neonates

We only have neonatal data from CareVue. You can confirm this pretty easily by subsampling your age distribution with `dbsource = 'metavision'` where `dbsource` is in the ICUSTAYS table. Any analysis that does not filter out neonates will see a big impact from this. I feel like this should be documented on the website somewhere, but I am not sure where - did you look at the documentation to try and figure this out? If so it'd be good to know where you looked so we can add it there.

### Blood cultures and antibiotics over time

A few things are happening here:

* Blood cultures have increased in frequency over time due to initiatives in the BIDMC (e.g. Multiple Urgent Sepsis Therapies 2 or MUST-2 which required blood cultures before antibiotics).
* The PRESCRIPTIONS table did not capture antibiotics until ~2003
* Antibiotics are not documented in INPUTEVENTS_CV - it wasn't routine practice - so there are no antibiotics documented in the intravenous tables for carevue patients*

\* For that last point, I actually found this out by querying INPUTEVENTS_CV for antibiotics and counting the number of observations for each `itemid`. I found that there were very few instances. If you search through your antibiotics list you should see the same for carevue - though I'd be interested to hear if you don't.

I think you'll find a plot we produced for a recent paper [1] interesting (the plot is in the [supplemental material downloadable here](http://links.lww.com/CCM/D208) and a snapshot of the jupyter notebook which generated it [here](
https://github.com/alistairewj/sepsis3-mimic/blob/9af529a0c15e8d8295dcfc521fd55ffd576d35e4/criteria-over-time.ipynb)) :

![image](https://user-images.githubusercontent.com/1282676/38279293-f8a3c8fe-3775-11e8-8c44-218fca183375.png)

As you can see, there are no prescriptions pre-2003, a large jump in blood cultures in 2008 (due to MUST-2 mentioned earlier), and antibiotic administration fluctuates at around ~65%.

### Defining antibiotics

I actually wrote a fairly detailed notebook on my process of extracting antibiotics for our recent paper, which you may find interesting. A static snapshot is [available here](https://github.com/alistairewj/sepsis3-mimic/blob/9af529a0c15e8d8295dcfc521fd55ffd576d35e4/appendix/defining-suspected-infection.ipynb). It goes over trying to extract it from prescriptions/inputevents. I'm not sure - do you actually use prescriptions in the end? The fact that you give a list of `itemid` seems to imply that you don't, but then your description of how you extract antibiotics discusses the prescriptions table, so I'm a little lost. Either way I think that notebook should help you a lot.

[[1] Johnson, A. E. W., Aboab, J., Raffa, J. D., Pollard, T. J., Deliberato, R. O., Celi, L. A., & Stone, D. J. (2018). A Comparative Analysis of Sepsis Identification Methods in an Electronic Database. Critical care medicine, 46(4), 494-499.](https://journals.lww.com/ccmjournal/Fulltext/2018/04000/A_Comparative_Analysis_of_Sepsis_Identification.2.aspx)

**Comment by geickelb** [comment]
I appreciate the through reply! 

to clear up about our antibiotic methodology, Since the PRESCRIPTION table does not have a "antibiotic y/n" column or an ITEMID column,  we only used the PRESCRIPTION table for NDC codes and labels. Using the NDC codes to convert to ATC codes, which does have antibiotic y/n annotations, we were able to flag the names of all the prescribed antibiotics from ~2003 and onward (according to your post). We then needed to convert these names into ITEMIDs, many of which had multiple ITEMID's for the same drug.

We noticed that antibiotic events are extremely rare (only captured ~3) in INPUTEVENTS_CV, whereas INPUTEVENTS_MV and CHARTEVENTS did contain antibiotic info. The difference being that INPUTEVENTS_MV had some antibiotic annotations and was linked to MICROBIOLOGYEVENTS, while CHARTEVENTS had no such link. That being said, we did find antibiotics recorded in CHARTEVENTS, (hence the big runaround to obtain a list of all the antibiotic associated itemid's). Our strategy was to grab all cases from CHARTEVENTS, and INPUTEVENTS_MV , merge them together, and flag/remove the duplicates. 

I appreciate the link to your paper and your sepsis3 coding, I will spend tomorrow reading through them! The big thing we want to investigate is: is our antibiotic coding and patient selection comprehensive or is it unintentionally biased.

**Comment by alistairewj** [comment]
OK, but do you use the rows from PRESCRIPTIONS in the end? Because the table actually contains each instance of the prescribed antibiotics for all the patients - not just the names of the antibiotics. So after you have all the drugs in PRESCRIPTIONS which are antibiotics, you can query for them to get all prescribed antibiotics for a patient.

How did you link INPUTEVENTS_MV to MICROBIOLOGYEVENTS? There's no obvious link from my memory!

**Comment by geickelb** [comment]
This is super helpful, it looks like we may have had a bit of a runaround when we could have used the prescriptions table for antibitiocs. The PRESCRIPTION start date/end dates are described as the time when the prescription is valid, however, for our study we need to know when the antibiotic was administered (which we were using INPUTEVENTS_MV and CHARTEVENTS for). Furthermore, the PRESCRIPTION  table doesn't have ITEMID, and the times from INPUTEVENTS_MV and CHARTEVENTS are much better representations of AB administration time. This is the original reason we used the antibiotic annotation runaround method I described earlier, because the times listed in PRESCRIPTIONS aren't granular enough, and there isn't a way to link that table to the chart/input events. 


I have two important questions on this table:

1)Given that we need a more accurate antibiotic administration time for each ab instance than the START/END time in PRESCRIPTIONS, do you know of a more direct way to link the rows in the prescription table with INPUTEVENTS_MV and CHARTEVENTS, or to get a more accurate administration time from the PRESCRIPTION table? Otherwise I, unfortunately, don't see how we can leverage the PRESCRIPTIONS table. 

1) is the DBSOURCE column in ICUSTAYS consistent with using the 'both' category? I have found around 50 SUBJECT_ID's that have rows marked cv and mv, and are not marked as "both" (see attached list). 



[cv_mv_pts.txt](https://github.com/MIT-LCP/mimic-code/files/1885678/cv_mv_pts.txt)

**Comment by alistairewj** [comment]
You could certainly cross reference prescriptions with the charted data for validation. It won't improve time resolution, but it would be interesting to study the relationship between the two. For example, vancomycin is often documented as "1 dose". To figure out the dose, you'd likely need to look at the prescription. I think a general analysis comparing these two tables would also be of great value to the community as a whole.

Regarding "both", these are the patients who you need to query both carevue and metavision tables to get data for. Otherwise, you don't need to. There is duplicate data in the two systems for other patients which you can safely ignore.
