### ISSUE TITLE
Understanding MICROBIOLOGYEVENTS + some documentation is missing

### ISSUE THREAD

**Issue by momih** [MIT-LCP/mimic-code#422]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description
I'm having a little trouble understanding the MICROBIOLOGYEVENTS table and [the official documentation](https://mimic.physionet.org/mimictables/microbiologyevents/) doesn't have information about the latter columns. So I had the following questions:

- Correct me if I am wrong: SPEC stands for the specimen collected for culture and ORG stands for organism growth observed and if ORG_ITEMID is null, then no growth occurred?

- I figured AB stood for antibiotic, but I don't understand what information those columns convey in this table. Is it just to explain that this antibiotic is *generally* given for this organism? Or is it the *specific* antibiotic that was administered for that HADM_ID? 
- The documentation lists a column called AB_CD but it's not present in my dataset?
- What does ISOLATE_NUM mean?
- What are the DILUTION columns for?
- The official documentations mentions that "If the specimen is null, then the culture had no growth reported." I don't think any of the SPEC_ITEMID is null, does it mean ORG_ITEMID instead?

**Comment by alistairewj** [comment]
Apologies for the lack of documentation - just added a bit but I would welcome a PR here if you find the time to tidy it up - particularly if you get more info from a microbiology specialist (which you should!). I'll answer what I can:

1. Correct, SPEC is specimen, ORG is organism. If ORG is NULL, then there was no growth (i.e. negative culture).
2. Correct, AB is antibiotic. They did not administer these antibiotics to patients. Instead, these are antibiotic sensitivities. If `ab_itemid` is present, then for a given dilution (`dilution_value`), you have a corresponding `interpretation`: "S" is sensitive, "R" is resistant, "I" is intermediate, and "P" is pending - did manage to document this at least! :)
3. `ab_cd` was an old column, it doesn't exist - in fact all `*_cd` columns were dropped as of v1.4
4. I'm not a biologist, but roughly from my understanding, `isolate_num` identifies different colonies of bacteria which grew on the same plate (and were probably further cultured/tested for sensitivity on other plates) - again though not a biologist, you might want to ask one instead of me
5. See above - dilution of the antibiotic tested
6. It does - spec should never be null, only org can be null.
