### ISSUE TITLE
About CRP

### ISSUE THREAD

**Issue by mylanhong** [MIT-LCP/mimic-code#427]
Dear Sir, 
      How can I extract the CRP (C-reactive protein) information for the first day in ICU.
      Thanks !!!

**Comment by tompollard** [comment]
Please follow the instructions at https://mimic.physionet.org/help/ when asking for help. Also, please follow the issue template.

> How can I get help with my analysis?
MIMIC is a complex dataset and we understand that there are many open questions, both in terms of the data and its analysis. We encourage MIMIC users to work together as a community, and actively participate in the discussion. If you are seeking advice for a specific question, we would suggest raising an issue on the MIMIC Code Repository. Please demonstrate that you have investigated the question yourself! Simply asking “how do I find X in MIMIC” is unlikely to garner any useful response, since it’s unclear what you have or have not tried yet.
