### ISSUE TITLE
Relating clinical data to matched waveform (mimic3)

### ISSUE THREAD

**Issue by arcrank** [MIT-LCP/mimic-code#441]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description

I am trying to link some of the fields in the clinical database to waveform numeric record files in the matched waveform database.  While the subject ID matches up, I am unable to determine how/if one can use the ICU stay IDs or hospital admittance IDs to relate information to a patient on a _record_ level.  As an example, the locations for some patients in matched waveform files is incomplete, but you can find information in clinical database (e.g. ICUSTAYS) but there does not appear to be a one to one correspondence.  Is there anyway to find out if a certain ICU stay aligns with one of the numeric records? I have tried for example also looking at date stamps, however these do not always line up fully for every record. 

Thanks

**Comment by alistairewj** [comment]
You can assign `icustay_id` and `hadm_id` using the timestamps from the clinical data. We would expect these identifiers to fully envelope waveform records, since waveforms are wholly derived from patients while in the ICU, but the reality is this doesn't happen because timestamps from the clinical data are documented by humans, thus have a "fuzziness" associated with them and may not precisely reflect time of admission/discharge. There are other issues, such as how the monitors kept track of time, which may cause inconsistencies. However, I've found that with a simple rule of adding 6 hours to either side of an admission window, you can match ~80% of clinical IDs to waveform records. You can read more about it in issue #86.

**Comment by arcrank** [comment]
Thanks for clarification.
