### ISSUE TITLE
inputevents_cv table has rows with 'rate' and 'amount' fields as null

### ISSUE THREAD

**Issue by schvetz1** [MIT-LCP/mimic-code#448]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hello,

At the inputevents_cv table, there are 1000 rows with null values at the 'rate' and 'amount' fields, I would like to know why and if I should ignore those lines?
In addition, in the fields 'originalrate' and 'originalamount' there are values in those cases, should I use those values instead? 

SELECT * FROM inputevents_cv where rate is  null and amount is  null
<img width="440" alt="null values" src="https://user-images.githubusercontent.com/33550773/43269892-7fd9e774-90fc-11e8-95ee-b24967178d61.PNG">

**Comment by alistairewj** [comment]
First, there are more than 1000 rows with null values. You may only see 1000 rows due to a limit applied by your user interface.

This may happen (1) because the treatment has stopped (see the `stopped` column), (2) because a new bag containing the compound has been placed (see the `newbottle` column), or (3) the caregiver is not documenting the rate/amount (e.g. `select * FROM inputevents_cv where icustay_id = 245846 and itemid = 30026 order by charttime;`).

You'll have to examine the data and, depending on what the compound being delivered is and how critical it is to your study, make a decision on how to handle these null values.

As mentioned [here](https://mimic.physionet.org/mimictables/inputevents_cv/#originalamount-originalamountuom-originalroute-originalrate-originalrateuom-originalsite) - the `originalrate` and `originalamount` columns refer to the starting rate/amount when the compound was added to the system. Keep in mind the `originalamount` is the amount in the bag at that time, not the amount delivered to the patient.
