### ISSUE TITLE
Hemoglobin typo in D_ITEMS table

### ISSUE THREAD

**Issue by kumarishikha** [MIT-LCP/mimic-code#462]
In D_LABITEMS table , there seems to be a typo for labels for Hemoglobin A and Hemoglobin S . Those are returned only after running the following query .
I googled a bit , and "Hemogloblin" does not seem to be a different existing terminology . 
SELECT * from D_LABITEMS where lower(d_labitems.label)  LIKE '%hemogloblin%'

**Comment by tompollard** [comment]
MIMIC, as far as possible, is real life data, complete with typos, errors, bad data etc. We intentionally share the data in this form because it is important for the community to develop solutions for handling these issues.

There are many typos in labels, particularly in the long tail of infrequently used ones. In this case, it looks like there are 264 patients with an `item_id` associated with `'%hemogloblin%'`, so a small but significant number.

We intend to work on an approach for collapsing `itemid`s in the future, and will share this work publicly. It is a difficult task to do well. In the meantime, I guess the question is how we help people to ensure they capture appropriate `itemid`s in their analyses (other than searching the code repository for issues/code). 

We'll leave the issue open for discussion and suggestions.
