### ISSUE TITLE
Temporal temperature data in MIMIC-3?

### ISSUE THREAD

**Issue by xorb22** [MIT-LCP/mimic-code#471]
Is there temporal temperature data for patients in MIMIC-3? I saw some papers in which temperature data is shown? But when I download numeric-form data, there is no temperature data. Am i missing something? 

Thanks for your answer

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
There is temperature data - but you must find it using the associated `itemid`. You may want to explore the [crrt-notebook](https://github.com/MIT-LCP/mimic-code/blob/8731b13c62698e82939b61c488fb31a231c01959/notebooks/crrt-notebook.ipynb) to better understand how to identify/extract concepts. Otherwise, you can look at the vital signs queries for temperature data: [vitals-first-day](https://github.com/MIT-LCP/mimic-code/blob/8731b13c62698e82939b61c488fb31a231c01959/concepts/firstday/vitals-first-day.sql) or [pivoted-vitals](https://github.com/MIT-LCP/mimic-code/blob/8731b13c62698e82939b61c488fb31a231c01959/concepts/pivot/pivoted-vital.sql).
