### ISSUE TITLE
Data to 2016 is planned to be added this fall?

### ISSUE THREAD

**Issue by EarlGlynn** [MIT-LCP/mimic-code#491]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

[AI Med](http://ai-med.io/), Vol 4, "The Case of MIMIC," p. 34:  "data to 2016 is planned to be added this fall)" to supplement the existing data between 2001 and 2012.  Can anyone comment on when this might happen, and how many additional records are being added?

**Comment by tompollard** [comment]
@EarlGlynn We are still working on the details! We prefer to avoid committing to dates because the work needs to fit around our research tasks and several different parties are involved, making deadlines tricky to keep. 

In terms of ICU records, the number should scale roughly proportionally with the additional years. We are hoping to supplement ICU data with additional ED data, OR data, and X-ray data. We are also rethinking the way dates/times are handled because the period of time is increasingly an issue.

Considering the amount of work that still needs to be done, I think this fall is unlikely. I'm sorry the article gave false promises, and we will do our best to share data with the research community as early as possible.

**Comment by bvandore** [comment]
Are there any updates on the timeline for release at this point? Any information you can provide would be greatly appreciated.

**Comment by alistairewj** [comment]
Please subscribe to this issue if you'd like to receive updates about MIMIC releases: https://github.com/MIT-LCP/mimic-code/issues/397
