### ISSUE TITLE
Bicarbonate values itemid

### ISSUE THREAD

**Issue by kumarishikha** [MIT-LCP/mimic-code#496]
For Blood gas analysis , should Bicarbonate values in inputevents* be considered  (itemid : 44166, 46362) or the ones in labevents (50882) ?

More generally , could someone explain how to decide which values to consider when similar variables are reported in labevents , chartevents , inputevents* ? I understand from the following link : https://mimic.physionet.org/mimictables/chartevents/  that "Some items are duplicated between the labevents and chartevents tables. In cases where there is disagreement between measurements, labevents should be taken as the ground truth. "  .  My main confusion is, its understandable that values may be repeated between the two tables  , but the itemids should have been consistent .

**Comment by alistairewj** [comment]
The `itemid` are intentionally distinct because these are recorded in distinct locations and may refer to distinct concepts. For example, the `itemid` 50882 is a bicarbonate:

```sql
select * from d_labitems where itemid = 50882;
```

 row_id | itemid |    label    | fluid | category  | loinc_code
-------- | ------- | ------------ | ------ | ---------- | -----------
83 |  50882 | Bicarbonate | Blood | Chemistry | 1963-8

This is the level of bicarbonate measured in the blood. Conversely, take a look at 44166 and 46362:

```sql
select itemid, label, linksto, category from d_items where itemid in (44166, 46362);
```

itemid |      label     |    linksto     |     category
---------| --------------- | -------------- | ---------------
44166 | BICARBONATE-HCO3 | | inputevents_cv | Free Form Intake
46362 | bicarbonate     | inputevents_cv | Free Form Intake

These are *inputs*, i.e. the patient was administered bicarbonate as a treatment. This is different to measuring the level of bicarbonate in the blood. The same name for an `itemid` does not indicate that it is the same concept. It may be the case that two `itemid` refer to the same concept but that is something that must be decided with some thought and investigation of the data.

**Comment by kumarishikha** [comment]
That explains it . Thanks !
