### ISSUE TITLE
outputevents - missing rows

### ISSUE THREAD

**Issue by Anat12345** [MIT-LCP/mimic-code#505]

**Comment by Anat12345** [comment]
Hi,

I start analysing different types of outputs, it seems like there are missing rows, 
for example hadm_id = 128632 has 23 days of foley but only 2 Fecal Bag,  1 Gastric Tube and 1 stool. it seems like not all the information was inserted to the table.
 **Is it possible that some data is missing?**
the query:
select subject_id, hadm_id, label, count(1), max(charttime)-min(charttime) as num_days from outputevents b,d_items a
              where subject_id in (45576,47118)
and a.itemid = b.itemid
and dbsource = 'metavision'
group by subject_id, hadm_id, label
order by subject_id, hadm_id, label

Thanks!
Anat

**Comment by alistairewj** [comment]
The "I think this should be there but it isn't" question is always very difficult to answer! What else would you expect to be documented?

**Comment by Anat12345** [comment]
I thought that maybe someone is more familiar with this table. 
The amount of of specific outputs is not reasonable , I don't think that many patients do not have stool for several weeks.
Is it any chance to check this with someone of the team of the hospital? which data is likely to be documented?

**Comment by alistairewj** [comment]
@lceli what do you think? Should more than UO be documented in MetaVision under outputs for a typical patient?

**Comment by lceli** [comment]
Output from drains are typically documented accurately. Stool amount is only documented when there is a rectal tube. Output is at best an approximation unlike input. Patients lose a lot of fluid through the ventilator when they are intubated, but that is never captured. The urine output is important because it reflects kidney function, but it's only an approximation of total. The best measure of whether a patient is "euvolemic" is daily weights.

**Comment by Anat12345** [comment]
Thanks for the detailed answer!
