### ISSUE TITLE
Question about itemid 228300 and 228337 in d_items tabel

### ISSUE THREAD

**Issue by Lvby** [MIT-LCP/mimic-code#524]
Hi, 

These two itemid label is very similar to each other in the d_items table.
  
| itemid         | label          | abbreviation |
| ------------- |:-------------:| -----:|
| 228300      | CAM-ICU MS change    | CAM-ICU MS change  |
| 228337    | CAM-ICU MS Change    |   CAM-ICU MS Change  |

After digging it a little bit deeper, I 've noticed their values are somehow different in the Chartevents table.

| subject_id (e.g.)     | label          | value|||
| ------------- |:-------------:| -----:|-----:|-----:|
| 13579      | CAM-ICU MS change    | Yes(Continue) | No(Stop-Not delirious)|
| 24680   | CAM-ICU MS Change    |   Yes                   | No  |Unable to Access|

Just report this issue, because it was a little bit confusing. 
If this is not the issue, please disregard it then. 

### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
This is a subtle issue and I'm happy for you to have raised it! These concepts are subtly different. The value is populated from a drop down box and as you can see, "Unable to assess" is an option for one but not for the other. That means that for one group of patients, they could be classified as "unknown", whereas the other group had to be "yes" or "no". The implications are subtle but important, as I've seen the proportion of cases with delirium increases because of this change!

**Comment by Lvby** [comment]
Thanks for the answer!
