### ISSUE TITLE
Blood pressure readings in different body parts

### ISSUE THREAD

**Issue by kumarishikha** [MIT-LCP/mimic-code#527]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
I went through the D_items table , looking for itemid regarding  blood pressure (systolic, diastolic, mean) . 
As an example, for systolic arterial blood pressure , using the following link : https://github.com/MIT-LCP/mimic-code/blob/master/concepts/firstday/vitals-first-day.sql
I understand following IDs should be used : 51,442,455,6701,220179,220050

But going through D_items table, I notice some IDs like 
3315	BP Left Arm [Systolic]
3317	BP Left Leg [Systolic]
3319	BP PAL [Systolic]
3321	BP Right Arm [Systolic]
3323	BP Right Leg [Systolic]
3325	BP UAC [Systolic]

Are readings taken at specific body parts not reliable for arterial blood pressure ?
Or, are the above readings (itemid 3*) referring to invasive readings, and  vitals-first-day.sql only consideres non invasive readings ? 
(I notice 220179 "Non Invasive Blood Pressure systolic" has been included in the vitals-first-day.sql)

**Comment by alistairewj** [comment]
These are infrequent recordings that I opted to not include in that query, for example compare the frequency of these to non-invasive mean blood pressure:

```sql
select itemid, count(*)
from chartevents
where itemid in (455, 3315, 3317, 3319, 3321, 3323, 3325)
group by 1 order by 2 desc;
```

itemid |  count  
-------- | ---------
455 | 1579681
3325 |   27586
3319 |   13380
3315 |    3762
3317 |    2052
3323 |    2039
3321 |    2032
```

**Comment by kumarishikha** [comment]
I understand . 
But there are no other qualitative issues apart from this which may justify leaving them out, right ?

**Comment by alistairewj** [comment]
Do not merge `itemid` simply because they both have names that sound the same. All measurements are made for a reason and you should strive to understand the context around that measurement. The most powerful way to do this is to look at the note. I took the first patient I found with itemid `3317` and looked at their nursing note that day: `select * from noteevents where hadm_id = 195786`

I found that this was a note for a neonatal patient. So I checked: what happens if I remove neonatal patients from my `itemid` count?

```sql
select itemid, count(*) from chartevents
where itemid in (455, 3315, 3317, 3319, 3321, 3323, 3325)
and hadm_id in
(
  select hadm_id from admissions
  inner join patients USING (subject_id)
  -- remove neonates (born within 1 year of hospital admission)
  where dob < (admittime - interval '1' year)
)
group by 1
order by 2 desc;
```

itemid |  count  
-------- | ---------
455 | 1579681
3325 |   0
3319 |   0
3315 |    0
3317 |    0
3323 |    0
3321 |    0

This resulted in 0 rows for the other `itemid`. They are all blood pressure measurements made on neonates. I recommend you do this type of investigation on all the data you collect otherwise who knows what you are basing your analysis on.

**Comment by kumarishikha** [comment]
Hey. Thanks for the info . 
In my pipeline, I am first picking up relevant patients (based on some other criteria) and will then get all relevant readings. So neonates patients would have been removed first.

But I agree that checks like you mentioned will reduce the complexity of the overall pipeline.

Thanks for the insight.
