### ISSUE TITLE
"There is No Such Directory Found" error

### ISSUE THREAD

**Issue by EhsanMasoumi** [MIT-LCP/mimic-code#532]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:
I have followed the Installation steps for windows. All steps seem to be fine except when I want to load the database using 

 \I   E:/Mimic_download/UnCompressed/postgres_load_data.sql

The error I get is that there is no such file or directory. 

I have following observations as well:
1- When pressing enter on first few lines at the beginning, I get this warning:
"Console code page (437) differs from Windows code page (1252) 8 bit characters might not work correctly."

2- If I use windows "\" instead of "/" to specify the directories I get error message "Permission Denied"

Thanks

Ehsan

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by alistairewj** [comment]
The build script needs to know where the data files are. We accomplish this by defining a `mimic_data_dir` variable: you can see at the top of that load data script that it calls `\cd :mimic_data_dir`. If this variable is unset, it doesn't change directory, and tries to load data from the local folder.

So more than likely you need either (1) set the variable appropriately or (2) call the script from the folder with the data.  Since you are calling `\i`, I presume you are running psql already. In that case, you can use:

`\set mimic_data_dir 'D:/mimic/v1_4'`

.. Depending on where your data is. If you haven't seen it, check out our [tutorial for windows](https://mimic.physionet.org/tutorials/install-mimic-locally-windows/) which runs through the process step by step.

P.S. The code page statement isn't an issue so don't worry about it.
