### ISSUE TITLE
PTT value CHAREVENTS table

### ISSUE THREAD

**Issue by vrandazz** [MIT-LCP/mimic-code#557]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

Good morning,
how is computed the PTT value stored in CHAREVENTS table (ITEMID = 227466)?
Does it refer to diastolic or systolic pressure?

**Comment by chris20881** [comment]
Hi @vrandazz, 227466 / PTT is a lab value, a coagulation test - Partial Thromboplastin Time, hope this helps, cheers, Chris

**Comment by vrandazz** [comment]
Hi @chris20881 Thanks for the answer. But the value of the PTT is related to the average blood pressure, maximum or minimum?

**Comment by chris20881** [comment]
Hi @vrandazz, can I ask why you feel PTT is related to blood pressure? Chris

**Comment by vrandazz** [comment]
Hi @chris20881 . I am interested in the values of ECG and PPG. How can I get them from the DB? Because I would like to find the relationship between these signals and blood pressure.

**Comment by alistairewj** [comment]
I think what Chris is trying to tell you is that the PTT you have found in chartevents is not pulse transit time.

Generally nurses do not document pulse transit time so you will be hard pressed to find it in the database. You may try using the matched waveform database, but we have no information about how well synchronized the ECG/PPG waveforms were, so that is a limitation of any analysis you do. Read about the matched waveform database here: https://www.physionet.org/physiobank/database/mimic3wdb/matched/
