### ISSUE TITLE
What is "mcg" unit in context of inputevents tables

### ISSUE THREAD

**Issue by kumarishikha** [MIT-LCP/mimic-code#559]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

For some items in inputevents_* tables, a unit 'mcg' has been used. 
eg:  for fentanyl :

221744
225942

Most cases I observed, the same itemid would use both mg and mcg as 'amountuom'. Also, there are lot of records with 'mcg' , meaning it is probably not just a typo.

Is it the same as milligram? Or does this have another meaning (maybe like mg per another unit like time/weight)?

**Comment by EdwardMoseley** [comment]
mcg should be "Microgram." 

The Greek prefix should be lower-case Mu but since our keyboards don't have the character easily accessible people will use "mc" for "micro."

Confusion probably occurs because I can't think of measurements other than mass which would be clinically relevant on the micro level.

**Comment by kumarishikha** [comment]
Okay. Thanks for the info.
