### ISSUE TITLE
 how to identify cardiac arrest and cardiopulmonary resuscitation

### ISSUE THREAD

**Issue by WenZhengSDU** [MIT-LCP/mimic-code#562]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
  Hi, everyone. Now I try to identify the cardiac arrest (CA) events and cardiopulmonary resuscitation (CPR) procedures, and want to determine the dates and times of CA events and CPR procedures.
  My questions are： some information about CA and charttimes  can be found in the chartevents and procedureevents_mv table,  while some CA and CPR information in the  diagnoses_icd and procedures_icd tables without times.  Could these variables cover all the CA and CPR ? If not, is there any other method to find these events and procedures completely?

**Comment by luojunqing** [comment]
I am not sure, but you can also find some CA events in DATETIMEEVENTS, NOTEEVENTS and  D_ICD_PROCEDURES tables.
If there are code status of CNI AND DNR in CHARTEVENTS, you shouldn't need to find CPR procedures.
BTW, if you can find CPR status in PROCEDURES_ICD, then you may find procedures times in the url [https://physionet.org/content/mimic3wdb-matched]

**Comment by lucky-qaq** [comment]
Hi, I want to find out the operative time for one of the subject_IDs in the Procedures_ICD table.
So, I extracted subject_id and seq_num from the Procedures_ICD table.
Then, subject_id and StartTime and EndTime are extracted from the ProcedureEvents_mv table.
Because seq_num is the order of operations
I want to be able to match the subject_id and seq_num to get the exact operative time.
My question is: With a random subject_id, I find that the total number of surgeries in seq_num is less than the total number of surgeries in the ProcedureEvents_mv table, and the number of surgeries in the two tables is not the same, so is it possible to find the time period by procedure order?How do you do that to actually match the ICD_9 operative time for the specific disease that the subject_id of the patient corresponds to?

**Comment by SichengH** [comment]
ICD Codes are billing codes, they don't store time-sensitive information in them. You might want to link patients and procedures with stay_id if they were in the ICU or hadm_id if stay_id is not there.
