### ISSUE TITLE
Error message on postgres_create_tables.sql

### ISSUE THREAD

**Issue by proton-code** [MIT-LCP/mimic-code#571]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

Brand beginner to MIMIC III and have minimal experience coding (only used SPSS and STATA before). 

I am following the instructions on the website: https://mimic.physionet.org/tutorials/install-mimic-locally-ubuntu/
I installed postgres by homebrew on a Mac and was able to finish step 1-5 then at step 7 I got the following error message

psql 'dbname=mimic user=mimicuser options=--search_path=mimiciii' -f postgres_create_tables.sql
**postgres_create_tables.sql: No such file or directory**

I assume something was wrong with postgres so I re-installed couples of times and it seems working just fine... but I kept getting this error message exactly at the same step...

I ran the brew list and am sure postgres is installed
"brew list
gettext		icu4c		pcre2		readline
git		openssl		postgresql"

Couldn't figure out what the problem is now

**Comment by alistairewj** [comment]
The command `psql 'dbname=mimic user=mimicuser options=--search_path=mimiciii' -f postgres_create_tables.sql` is essentially saying:

* `psql` - run postgres
` `'dbname=mimic user=mimicuser options=--search_path=mimiciii'` - with these parameters
* `-f postgres_create_tables.sql` - then execute the file "postgres_create_tables.sql"

The error message you are receiving is telling you "I can't find postgres_create_tables.sql". You need to copy those SQL files into the folder you are running the command in. I just updated the tutorial to be more clear about this. What you should do now is download all the files in https://github.com/MIT-LCP/mimic-code/tree/master/buildmimic/postgres that end in `.sql` and put them in the folder you are working in. It would be easiest to put the SQL files in the folder with the data, and run all the commands in that folder.

When downloading the files from GitHub you have to click the file and then at the top right corner right click "Raw" and click "Save as...". Otherwise the scripts won't work like in #402. See below for an example:

![image](https://user-images.githubusercontent.com/1282676/60923524-117c3b00-a26d-11e9-9de2-40978cf91946.png)

**Comment by proton-code** [comment]
IT WORKED! Thank you so much...  
I might come back with more questions but I will do my best to keep them less dumb.
Thank you again!

**Comment by alistairewj** [comment]
Great! Happy to hear!

**Comment by branholl** [comment]
I searched the directory and put everything in it and I am still getting the no such file or directory error. Theres no instructions on how to fix this error. All the instructions are vague and I dont see any videos or ways to fix this issue without being knowledgeable on the topic. I am a newbie here to this stuff.

**Comment by alistairewj** [comment]
Please open a new issue with further detail: the command you tried, the error message you received, and the operating system you are working on.
