### ISSUE TITLE
hospstay_seq is generated incorrectly in icustay_detail

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic-code#60]
> Mike found a likely bug in the icustay_detail generation (https://github.com/MIT-LCP/mimic-code/blob/master/demographics/postgres/icustay_detail.sql), where the hospstay_seq is generated incorrectly and always gives a 1 for some patients. See discrepancy below.

```
select count(1) 
from icustay_detail 
where hospstay_seq = 1 
and icustay_seq = 1;

 count 
-------
 57328
```

```
select count(distinct(subject_id)) 
from icustay_detail 
where hospstay_seq = 1 
and icustay_seq = 1;

 count 
-------
 46428
```

```
select * 
from icustay_detail 
where subject_id = 41976;

 subject_id | hadm_id | icustay_id |      admittime      | hospstay_seq |       intime        | los_icu | icustay_seq 
------------+---------+------------+---------------------+--------------+---------------------+---------+-------------+
... etc
(15 rows)
```

**Comment by alistairewj** [comment]
Was fixed in https://github.com/MIT-LCP/mimic-code/commit/4934f3aa5ef4106b607853a03d37e1e9c0bdfec0

`first_hosp_stay` = 'Y' if this is the subject's first hospital stay.
`first_icu_stay` = 'Y' if this is the first ICU stay for the given hospital admission (but *not* necessarily their first ICU stay ever, that would be found by checking `first_hosp_stay` = 'Y' and `first_icu_stay` = 'Y'.
