### ISSUE TITLE
Question: How can i find "Prone position/ventilation" records?

### ISSUE THREAD

**Issue by arielhasidim** [MIT-LCP/mimic-code#629]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
This is actually a question:
I want to find records about "prone ventilation" but I can't find a way to select them.
I already found out there is no ICD code for that.

**Comment by lceli** [comment]
We very rarely prone patients at Beth Israel Deaconess Medical Center. That is because we routinely use esophageal balloons to titrate PEEP and maximize alveolar recruitment. You will not find a decent sample size.Leo
    On Monday, October 14, 2019, 08:50:38 AM EDT, Ariel <notifications@github.com> wrote:  
 
 
Prerequisites
   
   -  Put an X between the brackets on this line if you have done all of the following:      
      - Checked the online documentation: https://mimic.physionet.org/about/mimic/
      - Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=


Description

This is actually a question:
I want to find records about "prone ventilation" but I can't find a way to select them.
I already found out there is no ICD code for that.

**Comment by arielhasidim** [comment]
Thank you very much for the quick and informative answer.
I will be also satisfied with very small sample (3-5). 
The big question is if I could find the information in the charevents table or maybe somewhere else?

**Comment by lceli** [comment]
You's have to look for that info from the nursing notes. I am skeptical that you'd find 3-5 patients who were proned. I've been there for almost 10 years and I have not seen a patient proned.
    On Monday, October 14, 2019, 09:01:31 AM EDT, Ariel <notifications@github.com> wrote:  
 
 
Thank you very much for the quick and informative answer.
I will be also satisfied with very small sample (3-5).
The big question is if I could find the information in the charevents table or maybe somewhere else?

**Comment by arielhasidim** [comment]
Anyway, you where very helpful, much obliged.
