### ISSUE TITLE
SOFA score

### ISSUE THREAD

**Issue by Aboelsoud** [MIT-LCP/mimic-code#64]
@alistairewj 
In the recent SOFA score code by Alistair, I think it should use lowest BP (MeanBP_Min)  not MeanBP_Max. 

Also, what happens if patient is missing PaO2 or FIO2?? 

Some patients will have O2 flow in Liter/min instead of FiO2. there are some conversion tables, e.g 2L =28% FiO2 but those are just approximate, also there's a modified SOFA score that uses SPO2/FiO2 instead of PaO2/FiO2 
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3811929/

Actually would be nice if anyone could create a code to calculate the modified SOFA in addition to the orginal one

**Comment by alistairewj** [comment]
That's a good catch regarding the blood pressure, thanks. It's fixed now.

If the patient is missing a PaO2 or an FiO2, they are given a score of 0 for the respiratory component.

It is possible to map O2 flow to FiO2 but you would need to know the O2 delivery device. Unfortunately at the moment we don't have that information for Metavision patients. Still, I'm not convinced it would be a very reliable proxy for FiO2, which is why I would hesitate to do it even if the data was available.

The modified SOFA looks interesting but I am not sure how we would define jaundice or scleral icterus. It would have to be regularly documented by clinical staff in a structured field to be readily derived and I haven't checked if it is.

**Comment by Aboelsoud** [comment]
Sorry Alistair, I meant a different study. It's the same SOFA but uses Spo2/FiO2 ratio

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3776410/

**Comment by Aboelsoud** [comment]
One more thing, I just extracted the SOFA for some patients, I found some of them will have blank in respiratory and others will have 0, can I assume that those blanks have missing data and the 0's have PaO2/FiO2 >400 so they scored 0?

**Comment by alistairewj** [comment]
That is exactly right. Missing data will be a missing PaO2, a missing FiO2, or both.

**Comment by lceli** [comment]
Fi02 is only reliable if the patient is on mechanical ventilation, non-invasive ventilation or high flow oxygen.

On Jan 29, 2016, at 4:56 PM, Alistair Johnson <notifications@github.com> wrote:

That is exactly right. Missing data will be a missing PaO2, a missing FiO2, or both.

**Comment by alistairewj** [comment]
Looks like that equation is only validated in ARDS patients. I'm not sure how applicable it is to the general population. I'll close this now, but if you're still interested in implementing a SOFA with SpO2/FiO2 instead of PaO2/FiO2, please do raise a new issue and we can discuss it further.
