### ISSUE TITLE
the overlap ICUSTAY_ID with the difference HADM_ID

### ISSUE THREAD

**Issue by lequangbkhn** [MIT-LCP/mimic-code#649]
I found a few duplicate ICUSTAY_ID? In the tutorial, are each ICUSTAY_ID unique to each SUBJECT_ID and HADM_ID?
ICUSTAY_ID: [209887, 275391, 203567, 292431, 200788, 216340, 235907, 296356, 207928, 226881, 272425, 266238, 291546, 206333, 219554, 223115, 235533, 235028]

**Comment by alistairewj** [comment]
Yep, unfortunately a known issue: https://github.com/MIT-LCP/mimic-code/issues/288

It's caused by the patients being discharged from the hospital and readmitted to the ICU in a very short (<24 hour) time period. In many of these cases, the patient wasn't actually discharged, but their `hadm_id` changed as they died in the ICU and were an organ donor.

**Comment by lequangbkhn** [comment]
Thanks Alistair.
