### ISSUE TITLE
Oldest supported version of Postgres?

### ISSUE THREAD

**Issue by ajb5d** [MIT-LCP/mimic-code#658]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

What is the oldest version of postgres that is currently supported by MIMIC?

I'm trying to build a copy of mimic in a singularity container and I noticed this line in buildmimic/postgres/Makefile:

    # if psql version is 10, then we can use declarative partitioning
    # this is done in the postgres_create_tables_pg10.sql file
    PSQL_MAJOR_VERSION := $$(psql --version | perl -lne 'print "_pg10" if / 10.\d+/')

- This doesn't correctly identify postgres versions > 10 
- It adds a perl dependency (I think it's the only usage of perl in the codebase)

I'm happy to supply a PR to resolve both these issues but figured it was worth checking that PG9 is still supported. If it's not, I'll supply a PR to drop PG9 support.

**Comment by alistairewj** [comment]
The main reason for that check is the use of declarative partitioning in the creation of chartevents. We also used ~100 partitions in PG10 rather than 10 since it was feasible and I found it faster.

The earliest version I think we would support is PG 9.4 because we make liberal use of the `DROP ... IF EXISTS` syntax, and then on top of that there are 1-2 scripts that use PG 9.4 features if I recall correctly.

We would welcome a PR! This was obviously a hack I did to get the code working :)
