### ISSUE TITLE
How to calculate mortality probability using SOFA, APACHE, SAPS score?

### ISSUE THREAD

**Issue by hhchang0210** [MIT-LCP/mimic-code#670]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

I'd like to use SOFA score to get AUC of mortality. As I know, it should have the mortality probability first so that I can get AUC. However, I am not able to find the formula to convert SOFA score into mortality probability. Only information I can find is a mortality rate table.
![註解 2020-01-17 050036](https://user-images.githubusercontent.com/42891908/72603072-581ab400-38e6-11ea-8d45-bed8638cc364.png)

Can anyone tell me a formula to convert it or any other ways to do it?

And I also curious about that how we convert APACHE or SAPS score to mortality probability.
The apsIII code from MIMIC code site shows probability = 1 / (1 + exp(- (-4.4360 + 0.04726*(APSIII) ))) 
The SAPS II code from MIMIC code site reveals probability =  1 / (1 + exp(- (-7.7631 + 0.0737*(SAPSII) + 0.9971*(ln(SAPSII + 1))) )) 
The OASIS probability = 1 / (1 + exp(- (-6.1746 + 0.1275*(OASIS) ))) from MIMIC code site

The APACHE II formula from https://clincalc.com/IcuMortality/APACHEII.aspx shows Hospital mortality may be calculated using the following equation: 
![註解 2020-01-17 050555](https://user-images.githubusercontent.com/42891908/72603513-2524f000-38e7-11ea-8bc9-c1eddd94adb1.png)

I wonder how we can know those formula. Could anyone give some hints to me?
Massive thank you.

Mikey

**Comment by alistairewj** [comment]
* You don't need probabilities to calculate an AUROC. The AUROC is a rank based metric and scale invariant.
* The APS-III and OASIS probabilities are from a calibration to a multi-center dataset; you can read more about how that's done in [Section 4.6.1 of my PhD thesis](https://ora.ox.ac.uk/objects/uuid:2486465e-8fda-47a9-b82e-c0a93f4f1fc4).
* The SAPS-II calibration is from their [SAPS II paper](https://jamanetwork.com/journals/jama/article-abstract/409979)
* It's not possible to create a probability for APACHE II (or III or IV for that matter) as the "admission indication weight" requires a coded diagnosis which we don't have in MIMIC (it's probably possible to make a surrogate from parsing the notes, but no one has done that to date). Otherwise that formula would be correct.

**Comment by hhchang0210** [comment]
Thank you for the reply. And that makes me know to calculate AUC as well.
