### ISSUE TITLE
ccs_dx - icd9_code

### ISSUE THREAD

**Issue by AguirreNicolas** [MIT-LCP/mimic-code#695]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

The next query, (where "%s" are tuples of icd9_codes)

text_sql = """
SELECT *
FROM mimiciii.ccs_dx DX  
WHERE DX.icd9_code IN %s;
"""
query_sql = cursor.mogrify(text_sql,(first_dgn_sql,))
dgn_group_df = pd.read_sql_query(query_sql, conn)

return me a many of codes with a ' ' (white space).

I did:
dgn_group_df['icd9_code'].str.strip()

to solve it, sice i was lossing subject in the way ...

I don't know if is an issue in mimiciii.ccs_dx table, or was mine ... 

for example, the code icd9_code = '4412', was '4412 '.

I could re-reun to have the rest of codes if it is needed

**Comment by alistairewj** [comment]
Yes this has to do with the way we released ICD-9 codes with MIMIC-III versus how they are distributed in CCS. CCS treats them as `CHAR(5)` but we treated them as `VARCHAR(5)`. The spaces are useful because they allow for queries like `between '440  ' and '441  '` - you can see we use them in the Elixhauser queries.

What I plan to do is add a derived view which merges the ICD-9 codes with CCS, that way everyone isn't caught up by this (very subtle!) inconsistency.

**Comment by AguirreNicolas** [comment]
Thank you for the quick response.
