### ISSUE TITLE
count mismatch between icustay_detail table and github query?

### ISSUE THREAD

**Issue by SSMK-wq** [MIT-LCP/mimic-code#700]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

Hello,

When we execute the query of icustay_detail (provided in github) directly in our console, the count that we get matches with the icustays table which is 46476

`select distinct subject_id from `physionet-data.mimiciii_clinical.icustays``   - 46476

The below short github query also gives 46476 subjects
```
select distinct subject_id from 
FROM icustays ie
INNER JOIN admissions adm                    
    ON ie.hadm_id = adm.hadm_id
INNER JOIN patients pat
    ON ie.subject_id = pat.subject_id    
```

However when we use icustay_derived table as it is, the count is different (lower)

`select distinct subject_id from `physionet-data.mimiciii_derived.icustay_detail`` - 46428

Is it like the code in github is updated but the table isn't updated?

Or Am I making any mistake here?

**Comment by alistairewj** [comment]
This is intentional as the `icustay_detail` table filters out some rows:
https://github.com/MIT-LCP/mimic-code/blob/a15dbd4d49330fb2a5f5b458d6a589979255f362/concepts/demographics/icustay-detail.sql#L47

Note that the BigQuery tables are built using the google-cloud-views branch, not the master branch. I do agree that this is unclear and we're thinking about how to better organize it.
