### ISSUE TITLE
Propagating indexes from CHARTEVENTS table to its inherited childrens

### ISSUE THREAD

**Issue by mornin** [MIT-LCP/mimic-code#71]
I just realized that when we run the current postgres_add_indexes.sql script. The 4 indexes will only be created on the mother table CHARTEVENTS. This can be meaningless, as there is no data in the mother table. The indexes will not automatically propagate to the children tables. Guess we may need to amend the script and create the indexes for each individual children table.

**Comment by tompollard** [comment]
Hey Mornin, I updated the [create tables script](https://github.com/MIT-LCP/mimic-code/blob/master/buildmimic/postgres/postgres_create_tables.sql#L176) a few days ago to generate partitions for chartevents because we needed to speed up a query for a workshop we were running. The indexes for the partition tables are generated in the same script, on itemids only. 

You're right we should review the [add indexes script](https://github.com/MIT-LCP/mimic-code/blob/master/buildmimic/postgres/postgres_add_indexes.sql) based on this recent update. For consistency the code to create the partition indexes could be moved to the [add indexes script](https://github.com/MIT-LCP/mimic-code/blob/master/buildmimic/postgres/postgres_add_indexes.sql) too. 

Further work is definitely needed on optimisation. We intend code in the MIMIC Code Repository to be developed collaboratively, so we'd welcome pull requests :) Otherwise we'll try to get onto this when there's time. 

On a side note, @parisni has been looking into indexes, partitions etc, and has also been [exploring alternative database](https://github.com/MIT-LCP/mimic-code/tree/86326ef86b2cc1a80f504126194fb7cd692221ca/buildmimic/monetdb) systems that might reduce and/or eliminate the requirement for indexes.

**Comment by mornin** [comment]
Hey Tom, I have updated the scripts and submitted a pull request. Hope it was done correctly.
