### ISSUE TITLE
Postgres vs. BigQuery for views in concepts

### ISSUE THREAD

**Issue by ajb5d** [MIT-LCP/mimic-code#717]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

What is the preferred dialect for queries in concepts? I see that there is a branch with the views for bigsquery but currently a couple of the views on HEAD reference the bigquery schema:

```
❯ grep -r physionet-data concepts/*
pivot/pivoted-invasive-lines.sql:    FROM `physionet-data.mimiciii_clinical.chartevents` ce
pivot/pivoted-invasive-lines.sql:    FROM `physionet-data.mimiciii_clinical.procedureevents_mv` mv
pivot/pivoted-invasive-lines.sql:    INNER JOIN `physionet-data.mimiciii_clinical.d_items` di
pivot/pivoted-icp.sql:  FROM `physionet-data.mimiciii_clinical.chartevents` ce
pivot/pivoted-fio2.sql:    FROM `physionet-data.mimiciii_clinical.labevents` le
pivot/pivoted-fio2.sql:  FROM `physionet-data.mimiciii_clinical.chartevents`
pivot/pivoted-fio2.sql:INNER JOIN `physionet-data.mimiciii_clinical.icustays` ie
pivot/pivoted-height.sql:  FROM `physionet-data.mimiciii_clinical.chartevents` c
pivot/pivoted-height.sql:  FROM `physionet-data.mimiciii_clinical.chartevents` c
pivot/pivoted-height.sql:  INNER JOIN `physionet-data.mimiciii_clinical.patients` pt
pivot/pivoted-height.sql:  FROM `physionet-data.mimiciii_notes.noteevents` ne
pivot/pivoted-height.sql:    FROM `physionet-data.mimiciii_notes.noteevents` ne
pivot/pivoted-height.sql:    INNER JOIN `physionet-data.mimiciii_clinical.patients` pt
pivot/pivoted-height.sql:    FROM `physionet-data.mimiciii_notes.noteevents` ne
pivot/pivoted-rrt.sql:  from `physionet-data.mimiciii_clinical.chartevents` ce
pivot/pivoted-rrt.sql:  from `physionet-data.mimiciii_clinical.inputevents_cv`
pivot/pivoted-rrt.sql: from `physionet-data.mimiciii_clinical.outputevents`
pivot/pivoted-rrt.sql:  from `physionet-data.mimiciii_clinical.inputevents_mv`
pivot/pivoted-rrt.sql:  from `physionet-data.mimiciii_clinical.procedureevents_mv`
```

I was looking to use the pivoted-rrt query in some new work.

I would suggest the following:
- Create subdirectories under concepts for the DBMS they target. The current concepts in HEAD would go to concepts/postgres and the google-cloud-views branch would be merged into concepts/bigquery

Happy to supply a PR if desired.

**Comment by tompollard** [comment]
> What is the preferred dialect for queries in concepts? 

It's a good question. Until recently, our preferred dialect was Postgres, but we're increasingly working in BigQuery.

> Create subdirectories under concepts for the DBMS they target. The current concepts in HEAD would go to concepts/postgres and the google-cloud-views branch would be merged into concepts/bigquery

I agree, moving all dialects to the master branch seems like the best approach for now. It is cleaner than maintaining separate branches. 

It will be a struggle to maintain multiple dialects, but that is a separate issue that we can deal with later. Ideally queries would be system agnostic.

**Comment by alistairewj** [comment]
Yep I'm just being unorganized in putting BigQuery queries in the master branch.

I kind of disagree about having two folders though; then you end up with two sets of identical code to maintain and they'll go out of sync. At least with branches you can use GitHub tools to visualize how up to date the other branch is and you can use rebase to try and sync changes (not that we've done a good job of that so far...).

**Comment by tompollard** [comment]
> I kind of disagree about having two folders though; then you end up with two sets of identical code to maintain and they'll go out of sync.

Out-of-sync is pretty much a given, regardless of where the SQL lives!

> At least with branches you can use GitHub tools to visualize how up to date the other branch is and you can use rebase to try and sync changes (not that we've done a good job of that so far...).

This is an interesting idea and not something I'd thought about. Not sure exactly how off of the top of my head, but you should be able to achieve the same thing with files on the same branch.  

Overall, I think clarity for users (all on same branch) outweighs the possible benefits of separate branches, but don't have strong views. Either way, I guess we need to clarify our approach.

To keep things as simple as possible we should be clear about a primary dialect (still Postgres?), which should always reflect the latest developments (and then other dialects can follow).

**Comment by lbulgarelli** [comment]
I think having both in one branch is the most user-friendly approach.

As for maintenance, maybe we should try and make queries database agnostic, maybe in a more granular way and then only have things that don't work on both in separate folders. Then we can write tests that assure that when a change is made the queries for each DBMS return the same result.

**Comment by tompollard** [comment]
> As for maintenance, maybe we should try and make queries database agnostic

Yep, good point! 

I don't think any of us have the time to do this right now, but we could work out a way of generating dialects from a primary source.

**Comment by ajb5d** [comment]
The biggest difference between the two dialects is that the current BigQuery views use a fully qualified table name (with the project). If we set a default dataset (or rather, required users to set a default dataset) then the views could use unqualified names (which are the same in postgres). This can apparently be done for the API calls (https://stackoverflow.com/questions/41265472/when-can-a-use-unqualified-tablenames-in-google-bigquery) but I can't figure out how to do it in the console.

There are a few corner cases where the dialects differ but I think the majority of the queries are nearly identical.

**Comment by alistairewj** [comment]
Closed via #762.

You're right that the scripts are almost all interchangeable. I ended up creating postgres functions which emulate BigQuery behaviour to reduce the number of changes needed in the scripts. On the left is BigQuery syntax, on the right is PostgreSQL syntax:

*  `SUBSTR(text, i, j)` -> `SUBSTRING(text FROM i FOR j)`
*  `DATETIME_DIFF(end, start, DATEPART)` -> `EXTRACT(EPOCH FROM end - start) / <datepart dependent>` \*\*
*  `DATETIME_ADD(datetime, INTERVAL n DATEPART)` -> `datetime + INTERVAL 'n' DATEPART`
*  `DATETIME_SUB(datetime, INTERVAL n DATEPART)` -> `datetime - INTERVAL 'n' DATEPART`
*  `DATETIME_TRUNC(datetime, DATEPART)` -> `DATE_TRUNC('datepart', datetime)`
*  `GENERATE_ARRAY(i, j)` -> `GENERATE_SERIES(i, j)`
*  `FROM table CROSS JOIN UNNEST(table.column) AS col` -> ????  (haven't worked on this one yet, see icustay-hours)
*  `'\x27'` -> Work around apostrophes in strings using LIKE '%text%'.
* `REGEXP_CONTAINS(text, r'pattern')` -> `text ~ 'pattern'`
* `DATETIME(date, hour, minute, 0, 0)` -> `CAST(TO_TIMESTAMP(date_as_char, 'DD-MM-YYYYHH24:MI') AS TIMESTAMP WITHOUT TIME ZONE)`
* ???(column) -> `PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY column)`    (not sure how to do median in BQ)

\*\* A regex is needed to quote HOUR, i.e. `DATETIME_DIFF(a, b, HOUR)` -> `DATETIME_DIFF(a, b, 'HOUR')`

The [postgres-functions.sql](https://github.com/MIT-LCP/mimic-code/blob/b1a0ffeae62a09fe3284650aceb578dad14fb9b1/concepts/postgres-functions.sql) script has some of the functions I wrote to emulate BigQuery.

In the end, all the scripts can be run directly in BigQuery (and [make-concepts.sh](https://github.com/MIT-LCP/mimic-code/blob/b1a0ffeae62a09fe3284650aceb578dad14fb9b1/concepts/make-concepts.sh) will generate them as tables). On the otherhand, [postgres-make-concepts.sh](https://github.com/MIT-LCP/mimic-code/blob/b1a0ffeae62a09fe3284650aceb578dad14fb9b1/concepts/postgres_make_concepts.sh) will make the tables in postgres. This works on my system but I'd appreciate testing since I'm sure I have custom/non-intuitive settings that are required! Closing this since I think it is handled (better to open more focused issues for anything that crops up from my refactor).

**Comment by zouzhiye** [comment]
DATETIME_DIFF(ad.admittime, DATETIME(pa.anchor_year, 1, 1, 0, 0, 0), YEAR) + pa.anchor_age AS age
how can I change this to "psql"?

**Comment by alistairewj** [comment]
Please raise a new issue if you have new a question!
