### ISSUE TITLE
What does a missing ICUSTAY_ID mean for the PRESCRIPTIONS table?

### ISSUE THREAD

**Issue by afalis** [MIT-LCP/mimic-code#720]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### If the ICUSTAY_ID for a HADM_ID is empty or '0,' does that mean the information is from a non-ICU area?

Specifically I'm looking at prescriptions. If a hospital admission has an order, but no ICU stay ID, does that mean the prescription was given on the floor? _OR_ was ICU stay not required to be filled out?

I can't seem to find the answer to this in the online documentation. Can someone point me in the right direction?

Thanks so much!!

**Comment by alistairewj** [comment]
You should not see any `icustay_id` or `hadm_id` with a value of 0.

This really depends on the table so I'll speak to prescriptions specifically. We assigned `icustay_id` to this table using their ICU admission/discharge time. If the row has an `icustay_id`, that means the prescription was made while the patient was in the ICU. However, because prescriptions often only have a date (and not a time), it's possible for inconsistencies related to dates vs. times. That is, a prescription to be made on `2120-01-01` for a patient in the ICU on `2120-01-01 14:00:00` could have been made for the patient while they were in the ICU, but it would not have an `icustay_id`.

`hadm_id`, on the other hand, are associated with the prescriptions in the raw data, and you can be sure if a prescription has an `hadm_id` it was made in the hospital.
