### ISSUE TITLE
Spurious lab values, etc

### ISSUE THREAD

**Issue by Mauvila** [MIT-LCP/mimic-code#749]
Regarding Mimic III lab events, are these taken directly from the Lab Information System software or the EHR?  The reason I ask is that many of the lab values I have run across recently are clearly spurious (probably due to IVF dilution).  Many hospitals will not report values that are obviously the result of contamination (by fairly simple algorithms), instead reporting them as "INVALID" or something similar in the EHR.  Is it possible that some of the lab values in MIMIC III were similarly flagged by the LIS, but that this fact didn't make it into the database?  
 
For example, pt ID 852, the labs drawn at 11/02/60 18:31, the Na is 84 (not compatible with life).  The glucose is 1601.  I feel most systems would have flagged all the labs from this lab draw, and not reported the actual values.  For MIMIC data analysis, it is not terribly difficult to implement the same algorithms that LIS systems use to flag these, but if this is needed, it would be useful to come up with a shared GitHub project to do it so that everyone is not re-inventing the wheel.

Also, probably not related to previously mentioned issue, I noticed that pt ID  8565 has a K value on 12/04/98 17:00 listed as "LESS THAN 10 mEq/L".  I would hope so, as serum potassium values >= 10 probably fatal.  Was this in the original database, or was this an artifact of the conversion to MIMIC 3 data?

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by Mauvila** [comment]
I think including annotations/comments would be great.  For lab values like extremely (unrealistic) low sodiums, they are suspect based solely on their values, so comments would reflect an algorithm run by the lab.   Annotations would be great, but not absolutely necessary for interpretation.  For other values, such as high Ks in the setting of hemolysis, comments by the lab usually reflect an additional visual examination of the specimen that can not be inferred from the lab values themselves.   So in order to interpret a serum K, one must know if hemolysis was present or not.   In these situations, annotations are essentially required for accurate interpretation of lab value. 

For the sake of automated analysis/machine learning, though, I feel the comments should be standardized.  Maybe from an enum (or whatever the informatics/ontology equivalent term is) consisting of "HEMOLYSIS", "SUSPECT CONTAMINATION", "PLATELET CLUMPING", some other things, and finally, "OTHER".  My hospital reports hemolysis using the same comment: "HEMOLYSIS PRESENT. HEMOLYSIS AFFECTS ALC, ALB, AST, CK, CKMB, DBIL, TBIL, GGT, K, IRON, LACTIC ACID, LD, MG, PHOS, TP, TRIG, AND URIC ACID".  So it wouldn't be hard to classify the hemolysis comments at my hospital appropriately.  Not sure about other types of comments.

In regards to the "LESS THAN" values, the sodium "LESS THAN 10" is probably ok.   It is totally acceptable to have "LESS THAN" values under certain conditions.  For "LESS THAN", the value is almost ALWAYS to the "left" of the reference range.  Likewise, for "GREATER THAN" values, the value is almost ALWAYS to the "right" of the reference range.  What is bizarre about the potassium value stated is that the "LESS THAN" value is way to the right of the reference range (ie the value is greater than the upper limit of normal).  Of course, with a human looking at the sodium value, there wouldn't be any confusion in recognizing the whole lab panel as invalid.  It is just curious that they chose 10 as their "LESS THAN" value for the potassium part.

**Comment by alistairewj** [comment]
I totally agree; in fact deidentifying this field has been on the internal issue tracker since October 1st, 2015 (!). From my experience, the lab comments mention one or more of the following:

* results with a operator (<0.01, greater than 70000, etc)
* results which are not numeric (positive, negative, equivocal)
* warnings about conditions that invalidate the lab result (hemolyzed among them)
* hemolyzed, icteric, lypemic, clotted, or clumped specimens
* previous errors which have been corrected
* verification of the current result
* reference ranges (particularly when it varies according to some other covariate like age, gender, etc)
* measurement specific information (e.g. cortisol values vary depending on the time of day due to circadian rhythm, stuff like that)
* misc observations (e.g. "large platelets" in the platelet count)

It would be great if there was an ontology for this that exists already that can cover this; it's pretty manageable. I can always ask the LOINC folks to take a look.

Ultimately, we'll include these lab comments in MIMIC-IV, and maybe the creation/standardization algorithms can be developed on that data, as it will be free-text.

**Comment by alistairewj** [comment]
The lab comments are de-identified in [MIMIC-IV](https://physionet.org/content/mimiciv/) and made available. The deidentification filtered ~5% of the comments, so there is still some room to improve it, though these comments were mostly "NOTIFIED DR. ___". Closing the issue and if something comes up we can discuss in a new issue at the MIMIC-IV repo: https://github.com/MIT-LCP/mimic-iv/
