### ISSUE TITLE
Oracle build script for noteevents fails due to newlines (\n) in the text

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic-code#75]
Oracle SQL Loader doesn't appear to support the [RFC 4180 format](https://en.wikipedia.org/wiki/Comma-separated_values) for CSVs, so the [control file for loading noteevents](https://github.com/MIT-LCP/mimic-code/blob/master/buildmimic/oracle/controlfiles/noteevents.ctl) fails.

The issue is that the text field contains newline (\n) characters, which Oracle treats as the end of a record. Surprisingly Oracle doesn't seem to offer a simple solution for this.

**Comment by alistairewj** [comment]
I've added a python script in https://github.com/MIT-LCP/mimic-code/commit/70425d1c5fb3c90e5821940b03929f9e54aee089 which adds newline characters and a build script for Oracle - maybe worth adding it to Jenkins next week?

**Comment by tompollard** [comment]
Tests added to the [tests folder](https://github.com/MIT-LCP/mimic-code/blob/master/tests/) will be run on Travis and Jenkins.

I've started to draft a template for the Oracle tests at: 
https://github.com/MIT-LCP/mimic-code/blob/master/tests/test_oracle_build.py

**Comment by visionnoob** [comment]
@tompollard any update on the test_oracle_build.py? 

We are trying to create an Oracle database.

Only the NOTEEVENTS table has not yet been successfully imported.
The SQL Loader does not start for this table. Error message is:
-----------------------------------------------------------------------
Path used:      Direct
SQL*Loader-500: Unable to open file (NOTEEVENTS_output.csv)
SQL*Loader-555: unrecognized processing option
SQL*Loader-509: System error: Error 0
SQL*Loader-2026: the load was aborted because SQL Loader cannot continue.
SQL*Loader-513: Unable to close file (NOTEEVENTS_output.csv)
SQL*Loader-559: error closing file
SQL*Loader-509: System error: Bad file descriptor

Table MIMICIII.NOTEEVENTS:
  0 Rows successfully loaded.

Check the log file:
  noteevents_output.log
-----------------------------------------------------------------------

Apparently, the SQL Loader has problems to find the data records within the CSV file. Compared to the other CSV files, the format is special in this case. The best results so far we could achieve by an import attempt through sqldeveloper, but in the end it was not successful too.

As described in the documentation we used add_oracle_rowdelimiter.py to prepare NOTEEVENTS.csv. We had to omit the parameter -r otherwise the script does not start. Nevertheless, the row delimiter seems to be set as expected.

Can you please guide us?

**Comment by visionnoob** [comment]
We managed to import all the tables with some minor modifications to the scripts. I'll create a pull request once everything is up and running.  For v1.4, this should be sufficient for anyone else to build it. 

If there is an upgrade to v1.4 with more data (or integration of another hospital's database etc) and henceforth LCP doesn't provide Oracle build scripts then we might have to do it ourselves, if our IT department continues with their Oracle-only service offer.

**Comment by tompollard** [comment]
@visionnoob thanks for the update and we look forward to the pull request. if you've overcome the newline issue, then hopefully (!) adapting the scripts for future data releases should be relatively straightforward.

**Comment by rolus-terminus** [comment]
@jsbhat and @tompollard: I have not been successful using the add_oracle_rowdelimiter.py script to prepare NOTEEVENTS. I saw in comments that the script assumes that the header is removed, so I took care of that. The script does not run (also omitted the -r parameter as mentioned above in post). Would either one of you be able to guide towards a solution, even if temporary? Oracle db is required for our use case to test alongside the Advanced Analytics toolset. Thank you.

**Comment by tompollard** [comment]
@rolus-terminus I'll try to take a look at this when I have a chance, but we no longer use Oracle in the lab so would encourage input from the community. In case it's of interest, we provide Python at https://github.com/MIT-LCP/oracle-to-postgres to migrate content from Oracle to Postgres.

**Comment by tompollard** [comment]
> do the provided MySQL scripts work as intended?

Oracle is the only database that caused us problems, because it didn't (doesn't?) handle the RFC 4180 standard for CSVs.

Loading to MySQL should be fairly straightforward, though the MySQL scripts may be outdated. If they need updating we'd welcome your contributions.  

Our lab uses Postgres and Bigquery, so these are the only scripts that we actively maintain ourselves.

**Comment by tompollard** [comment]
As a side thought, it might be worth contacting Oracle to see if they can explain how to load a RFC 4180 formatted CSV into their database. If you get a helpful reply, please post the solution here :)
