### ISSUE TITLE
Newborn method of delivery is not available in the database

### ISSUE THREAD

**Issue by gbf1112** [MIT-LCP/mimic-code#768]
Dear Teacher,

### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

I'm a newborn professional, I can't find a way to deliver a newborn in Table: mimiciii.chartevents, 
only find  "7634"	"Cesarean delivery aff NB"	"Cesarean delivery affecting fetus or newborn" , but is only two.

I hope you can give me some help and answers.

**Comment by alistairewj** [comment]
You're right in that there isn't documentation of this in chartevents; which sort of makes sense, since that is all in ICU documentation.

The best way to determine this are the billed ICD diagnoses, in particular the V30-V39 codes:

```sql
SELECT di.icd9_code, di.long_title
, count(dx.hadm_id) as n
FROM `physionet-data.mimiciii_clinical.d_icd_diagnoses` di
INNER JOIN `physionet-data.mimiciii_clinical.diagnoses_icd` dx
ON di.icd9_code = dx.icd9_code
WHERE dx.icd9_code like 'V3%'
GROUP BY 1, 2
ORDER BY 3 DESC
```

Here are the top two rows returned by that query:

icd9_code | long_title | number of hospitalizations
--- | --- | ---
V3000 | Single liveborn, born in hospital, delivered without mention of cesarean section | 3566
V3001 | Single liveborn, born in hospital, delivered by cesarean section | 2758

**Comment by gbf1112** [comment]
Thank you very much！
