### ISSUE TITLE
MIMIc-iii: Redundant icd-9 procedure codes

### ISSUE THREAD

**Issue by kim-gradel** [MIT-LCP/mimic-code#780]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Description of the issue, including:

In the documentation of the MIMIC-iii table D_ICD_PROCEDURES is written that each ICD-9 code "corresponds to a single procedural concept". This does not seem to be true. The table has 3809 codes, of which 73 have 2 text meanings. An example:

ICD-9 code 744 has two observations, one defined as "Cesarean section NEC", the other as "Adrenal repair", which are two quite different procedures.

I have looked at the documentation and tried to find similar issues in GitHub, but all in vain.

* what you have tried
* references to similar issues
* queries demonstrating your question (if applicable)

**Comment by tompollard** [comment]
The two rows in the [d_icd_procedures table](https://physionet.org/content/mimiciii-demo/1.4/D_ICD_PROCEDURES.csv) from your example are:

```csv
row_id,icd9_code,short_title,long_title
398,0744,Adrenal repair,Repair of adrenal gland
3144,744,Cesarean section NEC,Cesarean section of other specified type
```

The `icd9_code` column should be stored as a string. The data type is important, because if treated as numbers the leading `0` is lost. These codes are described on the following webpages:

- `0744` codes for "Repair of adrenal gland": https://www.rxdb.com/icd9pcs.0744
- `744` codes for "Cesarean section of other specified type": https://www.rxdb.com/icd9pcs.744

**Comment by alistairewj** [comment]
Yeah possibly due to the bug referenced in #737

**Comment by tompollard** [comment]
Yep, the icd9_codes in `d_icd_procedures` and `procedures_icd` were stored as integers on bigquery. Thanks for raising the issue @kim-gradel. The tables have now been fixed.
