### ISSUE TITLE
Heart rate in MIMIC III and MIMIC III Waveforms

### ISSUE THREAD

**Issue by Sunny-star** [MIT-LCP/mimic-code#782]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Hi Alistair,
I want to do some analysis with the data of heart rate. 
By searching with the itemid= 220045, I found there were 2,762,225 heart rate records of 17,714 subject_id. And the time interval of measurements ranged from several minutes to hours. Because I need the heart rate as much information as possible, my question is if MIMIC-III Waveforms Database has more information about heart rate, or the MIMIC-III Clinical Database is enough.
Thanks !

**Comment by alistairewj** [comment]
It really depends on what you want to do, but here are the trade-offs:

* Every patient will have heart rate documented in the clinical database. Conversely, only ~20% of patients are in the waveform database.
* Patients usually have a heart rate documented every hour, on the hour. Sometimes it's more often, rarely it's less often. Waveform heart rates are available every 1 minute.
* Both measurements are from the same device (a bedside monitor), which takes a ~5 second median (or something similar). However, due to slightly different timing in the calculation of the median, the waveform data and clinical data are usually slightly different even if both are documented for the same minute.

Hope that helps!

**Comment by Sunny-star** [comment]
Thank you a lot, it really helps me a lot!
