### ISSUE TITLE
chartevents table is very huge for importing

### ISSUE THREAD

**Issue by parisaetemadinejad** [MIT-LCP/mimic-code#796]
I have to add chartevents table to pgadmin 4. i write this code 
copy CHARTEVENTS from 'path of my CSV file in my PC' delimiter ',' csv header NULL '';
and I see this error :
ERROR:  Could not stat file "path of my CSV file in my PC": Unknown error
SQL state: XX000
please help me
thanks alot

**Comment by alistairewj** [comment]
It looks like you are running the command wrong, since it is trying to load the text `path of my CSV file in my PC` as a file (and obviously that's not a file name).

You might find it easier to use the ready to go database on a cloud platform like BigQuery: https://mimic.physionet.org/gettingstarted/cloud/
