### ISSUE TITLE
PostgreSQL build scripts import an empty string instead of NULL

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/mimic-code#81]
There are many string fields in the database which have null values, for example, the `DESCRIPTION` field in CPTEVENTS. The build scripts for PostgreSQL import these as an empty string rather than NULL. 

In Oracle:

```sql
select count(description) from mimiciii.cptevents;
```
Returns 101545.

In PostgreSQL:
```sql
select count(description) from mimiciii.cptevents;
```
Returns 573146.

Hopefully there is a setting somewhere which tells PostgreSQL to interpret empty strings (i.e. "" in the csv) as NULL values rather than blanks. Either that or we could modify the export scripts to not export double quotes when the field is null - not sure which is more appropriate.

**Comment by pszolovits** [comment]
Seems to me that if the value is NULL, Oracle should export a textual representation of NULL, not an empty string.  I dealt with this in importing to MySQL by explicitly testing in the LOAD DATA statement and turning empty strings into NULLs, and the same could be done in the PostgreSQL version of data import.  However, the right fix would be to fix Oracle.  I’m not sure, however, if there is a universally accepted way to represent NULL in a csv file.  Certainly “” is correctly treated as the empty string, nothing between two commas is also treated as the empty string,  and NULL is treated as the string “NULL”, I think.  I believe MySQL uses \N as the representation of a NULL in a text file to be imported, but I don’t know if other SQL databases follow this convention.  Oracle seems not to, or else it would output NULLs as \Ns.

**Comment by alistairewj** [comment]
Well, now that you mention it, I remember you
having difficulty with that...
at the moment, our scripts output all
the double quotes manually, so we could
edit the scripts to instead output no quotes,
then consider a lack of double quotes as
evidence that the field should be null, but as of
right now I haven't tested if postgres would easily understand that.

Probably the best solution involves not
encapsulating a special character unless
there's no other option, but if we have to then we should strongly
emphasize it in the documentation.

**Comment by alistairewj** [comment]
Also it's worth mentioning that doing the export with a special case for
treating empty strings as null and not outputting double quotes would make
the code look long and ugly. Might be nicer to have import side solutions.

**Comment by pszolovits** [comment]
It should not have to be a special case.  Oracle obviously distinguishes internally between a text field that contains “” and one that contains NULL.  It’s a bug for it not to distinguish those in its output. If both are represented identically, then exporting and re-importing data loses information.

My preference would be to treat “” as an empty string and nothing-between-commas as NULL.  However, from what I read via Google searches, such a nothing-between-commas is not treated consistently as NULL by various systems’ import functions. I think part of the variability of interpretation has to do with declared default values for columns; some import routines take nothing-between-commas to mean use the default for that column rather than NULL.

**Comment by alistairewj** [comment]
So I just tested this by running sed to replace the double quotes from the microbiology table:

```sh
sed -i 's/""//g' MICROBIOLOGYEVENTS.csv
```

And it seems PostgreSQL is happy with this format - it treats elements with no double quotes as NULL rather than as an empty string. We haven't been able to import the NOTEEVENTS csv's into Oracle (mainly because new lines break it), but it's worth testing if this works for the other tables. How would this affect MySQL? Does your custom import code already handle such a situation?

**Comment by pszolovits** [comment]
My MySQL import code deals with it by reading the LOAD DATA INFILE data into local variables and then setting the columns with expressions like
CHARTTIME = IF(@CHARTTIME='', NULL, @CHARTTIME),
Of course because the distinction between “” and NULL was lost in Oracle’s export, I can’t recover it, and thus treat all empty strings as representing NULL.

The following works for importing NOTEEVENTS into MySQL:
LOAD DATA LOCAL INFILE 'NOTEEVENTS.csv' INTO TABLE NOTEEVENTS
   FIELDS TERMINATED BY ',' ESCAPED BY '\\' OPTIONALLY ENCLOSED BY '"' 
   LINES TERMINATED BY '\n'
   IGNORE 1 LINES
   (@ROW_ID,@SUBJECT_ID,@HADM_ID,@CHARTDATE,@CHARTTIME,@STORETIME,@CATEGORY,@DESCRIPTION,@CGID,@ISERROR,@TEXT)
 SET
   ROW_ID = @ROW_ID,
   SUBJECT_ID = @SUBJECT_ID,
   HADM_ID = IF(@HADM_ID='', NULL, @HADM_ID),
   CHARTDATE = @CHARTDATE,
   CHARTTIME = IF(@CHARTTIME='', NULL, @CHARTTIME),
   STORETIME = IF(@STORETIME='', NULL, @STORETIME),
   CATEGORY = @CATEGORY,
   DESCRIPTION = @DESCRIPTION,
   CGID = IF(@CGID='', NULL, @CGID),
   ISERROR = IF(@ISERROR='', NULL, @ISERROR),
   TEXT = IF(@TEXT='', NULL, @TEXT);
That’s because once we struggled through the bugs in exporting with improperly used \, the csv files now contain properly formatted multi-line quoted strings.  Note that in NOTEVENTS, just ROW_ID, SUBJECT_ID, CHARTDATE, CATEGORY and DESCRIPTION can’t be NULL.

**Comment by alistairewj** [comment]
Yes, our CSV files are nicely formatted now, but Oracle still can't handle
them without a lot of work (I'm also half convinced that it can't handle
multi-line CSVs *at all* without adding a custom end of row character to
the raw data).

Oracle doesn't differentiate between an empty string ("") and NULL. You
can't even have data elements in the database which are empty strings - it
will set them to NULL automatically. So we can't expect it to ever
differentiate between the two in the export process unless we manually tell
it to. Probably we will do this because it works with PostgreSQL. If we
changed the logic so that ,"", actually represented an empty string, and an
empty value ,, represented a NULL, would your MySQL scripts be simplified?

**Comment by pszolovits** [comment]
I didn’t realize Oracle failed to make that distinction, which seems odd.  I’ll have to investigate how well MySQL’s LOAD DATA would respect the distinction between ,, and ,””, .  I’ve read some posts that suggest that there is an interaction with default column value declarations and some inconsistency, so I’m not sure.

The fundamental question for MIMIC is whether there is actually a distinction in our source material between empty strings and NULLs.  If not, then we could adopt your approach of just treating all empty strings as NULL and not have to solve this problem.

**Comment by alistairewj** [comment]
I think there isn't a distinction between the two, so I've updated the PostgreSQL scripts to reflect that an empty string should be imported as NULL. If it comes up as an issue and an empty string actually carries meaning in the future than we can re-open this issue. Thanks for the discussion.
