### ISSUE TITLE
NOTEEVENTS not a well-formed csv?

### ISSUE THREAD

**Issue by jvddGit** [MIT-LCP/mimic-code#820]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

The NOTEEVENTS csv file seems to have some problems. Even the quick preview on the web site illustrates that it appears to have column delimiter problems (some rows delimited with tabs, some with commas?) as well as many CRLF characters in some of the text fields.  Or do I have the wrong idea of how this file should behave?

**Comment by tompollard** [comment]
The table is formatted according to the [RFC 4180 specification](https://tools.ietf.org/html/rfc4180), as far as I recall. If you'd like to post `row_id`s for specific rows that you believe are malformed, then we can take a look.

**Comment by jvddGit** [comment]
The row_id values that I'm looking at are 174, 175, 176, 177--the first four rows in the file.  But I suspect there's something pervasively wrong going on.

**Comment by tompollard** [comment]
I think the issue is that you're looking at a rendering of a zip file in the browser, which does look a bit screwy I agree. Try downloading the file, unpacking to CSV, and looking at that. If you notice issues when importing the file for analysis, please post your code and the error message.

**Comment by tompollard** [comment]
From a quick glance at the text, it looks like break immediately after "foci of high T2" (row_id = 175) is due to a new line character:

`foci of high T2\nsignal within the white matter of both cerebral hemispheres\nas well as the pons, in the latter region predominantly to\nthe right of midline.`

As far as I can see, RFC 4180 is okay with new lines in this case:

> 6.  Fields containing line breaks (CRLF), double quotes, and commas
>   should be enclosed in double-quotes.  For example:
> 
>     "aaa","b CRLF
>     bb","ccc" CRLF
>     zzz,yyy,xxx

So I think the issue is that the web renderer is incorrectly treating the new line as the end of the row (possibly related to the fact that the file is zipped, though not sure without investigating).
