### ISSUE TITLE
Variable Selection Problem

### ISSUE THREAD

**Issue by Delia5353** [MIT-LCP/mimic-code#822]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I have been doing a research,I have been doing a research and now I need to filter out the variables I am interested in from many itemids.
* what you have tried
But I found that one variable corresponds to multiple itemids, and I don't know how to choose. I also hope that seniors can point me to the method of locating itemid according to the variable name.
*example
For example, Systolic blood pressure, when you search in the d_items table, you will find that there are many corresponding variables, and I cannot associate my variable name with itemid。

**Comment by alistairewj** [comment]
You will need to use multiple `itemid` for a single concept as they are not guaranteed to be documented with the same `itemid`. You can use the code available in this repository as a starting point since we have many concepts already coded (e.g. systolic blood pressure is in the pivoted vitals query: https://github.com/MIT-LCP/mimic-code/blob/1dd6637f47c83fe685176534b770e37b7fb48ef9/concepts/pivot/pivoted_vital.sql)

**Comment by Delia5353** [comment]
Ok,i got it.Thank you very much!
