### ISSUE TITLE
 MIMIC IV Chest x-ray database, Neonate, MIMIC III

### ISSUE THREAD

**Issue by ServehPadash** [MIT-LCP/mimic-code#838]
Hi Alistair,
I have some questions and would appreciate your help. In the video tutorial, you mentioned MIMIC IV includes a high number of neonate patients.
1-I found that 60879 numbers of patients have an anchor-age of zero. I think they are neonates right? but in  MIMIC  IV CXR there were not any subject ID with an anchor-age of zero. I am wondering if the CXR file of the database includes any neonates patients?
if no what kind of information associated with neonates cases are available in the dataset?
2- I also went through the MIMIC III articles. Does MIMIC include CXR images of the patients?
Thank you

**Comment by alistairewj** [comment]
> 1-I found that 60879 numbers of patients have an anchor-age of zero. I think they are neonates right? but in MIMIC IV CXR there were not any subject ID with an anchor-age of zero. I am wondering if the CXR file of the database includes any neonates patients?

Since you mention anchor age, this is probably a MIMIC-IV question, which you should ask over in the MIMIC-IV repository: https://github.com/mit-lcp/mimic-iv

There shouldn't be any neonates in MIMIC-CXR. Only those who went through the ER were included and neonates don't do that typically.

> if no what kind of information associated with neonates cases are available in the dataset?

Only MIMIC-III has ICU data for neonates, and that's only from Carevue (2001-2008).
