### ISSUE TITLE
Merge ITEM_ID from metavision and carevue 

### ISSUE THREAD

**Issue by cynthiazeng** [MIT-LCP/mimic-code#848]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description
Dear MIMIC data provider,

I am wondering if there is a way to consolidate the D_ITEMS number system between metavision and carevue. It seems for metavision items have large values > 220000. For instance, blood pressure value would have two distinct item numbers due to different providers. Is it possible to have just one number system? 

Thank you very much,

Cynthia

**Comment by alistairewj** [comment]
We left the data as is - when creating the database we tried not to apply our own assumptions onto it. Mapping `itemid` together is intractable in general (because it's not always a one to one conversion), but if you look through the repository you'll see the most common concepts are queried and you could infer the mapping from the SQL scripts. I believe there are some other issues where users have contributed their own mappings (just keep in mind these mappings are often study specific, e.g. some researchers merge SpO2 with SaO2 though they are strictly not the same).
