### ISSUE TITLE
cptevents has no charttime values

### ISSUE THREAD

**Issue by Erinaceida** [MIT-LCP/mimic-code#856]
The cptevents table has no charttime values, even though according to the documentation it should. Is there a way to get that timestamp via a link?

**Comment by alistairewj** [comment]
Unfortunately the error is the other way around. There is no `charttime` for CPT codes and the documentation is incorrect. I'll look to update the docs when the new release of MIMIC-IV is out.

In MIMIC-III there was a `chartdate` column but that was because we added respiratory therapist billed CPT codes to the table. The hospital billed CPT codes never had a date. We don't have access to physician billed CPT codes in general so they won't be in MIMIC-IV.

If you're looking for timing of billed procedures you might try the *procedures_icd* table in the next version of MIMIC-IV which will have a `chartdate` column.

**Comment by Erinaceida** [comment]
Thanks for your reply! shame, cptevents has some high-level data that would be easy to analyse. 
May I ask when the new MIMIC version is going to be released?

**Comment by alistairewj** [comment]
Very soon! The new release has been uploaded to PhysioNet so there will be a (hopefully short) review process before it goes out.

And I was wrong in my previous post. After double checking with hospital staff it is possible to get dates for CPT codes. They'll be in the next release. I did note the CPT codes we are distributing with MIMIC-IV may be different to those included with MIMIC-III (in terms of their approximate content), so worth keeping that in mind. Hard to say exactly because there are neonates in MIMIC-III and they obviously have a very different profile than adult patients.

**Comment by Erinaceida** [comment]
It's been almost a month and the database update hasn't been released yet. Can we have a bit more detail as to when it is going to happen, please? The reason I'm asking is that there is a JBI call for papers (https://www.journals.elsevier.com/journal-of-biomedical-informatics/call-for-papers/innovative-informatics-methods-for-process-mining-in-health) with a deadline on the 1st of June.

**Comment by alistairewj** [comment]
Released today and notes are here: https://mimic-iv.mit.edu/docs/overview/changelog/#mimic-iv-v10

**Comment by Erinaceida** [comment]
That's great, but I can't find CPTEVENTS table in the new release?

**Comment by lbulgarelli** [comment]
> That's great, but I can't find CPTEVENTS table in the new release?

> Has it been renamed to procedureevents_mv ?

MIMIC-IV does not contain a `cptevents` table. CPT codes are a subset of HCPCS codes, which are now included in the database. You can find this data in the table `hcpcsevents`.
