### ISSUE TITLE
Kdigo_stages: why half the period?

### ISSUE THREAD

**Issue by EvaniLach** [MIT-LCP/mimic-code#864]
Hi,

I had a question about [kdigo_stages](https://github.com/MIT-LCP/mimic-code/blob/master/concepts/organfailure/kdigo_stages.sql), lines 44-49.
I was wondering why the script requires the UO to be calculated over half the period? Cause this doens't comply with the KDIGO guidelines. In theory this script will sometimes overestimate the AKI stage? F.e.: if a urine output is <0.3 and calculated over a period of 12 hours, the script will label it as AKI stage 3. However, for stage 3 it'd need to be below 0.3 for at least 24 hours.

Is it maybe to make sure you've got enough data?

**Comment by alistairewj** [comment]
https://github.com/MIT-LCP/mimic-code/blob/d512dee7447564bfa94ee85c14875d9e9a5fac28/concepts/organfailure/kdigo_stages.sql#L44-L49

Just to clarify, in the case of the 24 hour AKI, it's not It's important to highlight that the restriction isn't "calculate the UO over 12 hours", it's "calculate AKI over 24 hours, and require documentation to exist for *at least* 12 hours" (i.e. half the period). The goal is to ensure the UO documentation reasonably covers the 24 hour period.

The problem with looking at a 6/12/24 hour period without this restriction is you end up with a patient having a UO of 300 mL on hour 0, then no documentation for 24 hours, and therefore they have AKI stage 3. In reality, they may have had their foley removed, or who knows. In general I found without this limitation the approach was vastly overestimating AKI due to lack of UO documentation.

It's just an idea I had and it certainly isn't in the guidelines. The consequence is of it is the AKI rule becomes "calculate UO over 24 hours, and if you can't do that exactly, then feel free to extrapolate from anywhere between 12-24 hours". Alternatively you could look at a period greater than 24 hours and downsample.. but in general it's not clear what to do when you don't have the perfect hourly UO documentation.
