### ISSUE TITLE
Culture orders for patients from Emergency Department(Ed)

### ISSUE THREAD

**Issue by fatemeh91** [MIT-LCP/mimic-code#930]
Hi,
The number of patients in  ED who have been  received an order for antibiotics is significantly lower than the number of ED patients  who received antibiotics. is there any justification for it?

**Comment by alistairewj** [comment]
Your issue is probably this join:

```sql
    from allcultures c inner join EDptendinICU p
    on p.hadm_id = c.hadm_id and p.subject_id = c.subject_id and p.charttime = c.charttime
```

You're doing an exact join on charttime - one of which is whenever the blood culture is maid (`c.charttime`), and the other (`p.charttime`) is generated as every hour from the patient's intime (in your patients_hosp_stay table `generate_series(intime, outtime, interval '1hours') charttime`). So you're basically requiring that, if a patient is admitted at `12:32`, their blood culture is measured at either `12:32`, `13:32`, `14:32`, ..., etc, otherwise you won't capture it. This will drop *a lot* of data. You should look into using something other than exact time matching for linking the patient info with the culture info.
