### ISSUE TITLE
Medication mapping between mimic ii and iii

### ISSUE THREAD

**Issue by edwardluotw** [MIT-LCP/mimic-code#94]
I am migrating from MIMIC-II to III and need to find corresponding medication mapping.

For example, `itemid = 51` in `d_meditems` table corresponds to Vasopressin in MIMIC-II.
Also, the query `select * from mimic2v26.d_meditems where lower(label) like '%vasopressin%'` also return a single entry about Vasopressin.

In MIMIC-III, I know `d_meditems` table is merged into `d_items` table.
Therefore, I tried to find corresponding Vasopressin in `d_items` table using the following  query.
`select * from d_items where lower(label) like '%vasopressin%'`

I think the rows with inputevents_cv in linksto column are the potential candidates I am looking for.

```sql
Vasopressin	           |	  | carevue	|   inputevents_cv   |    	            |                                  
VASOPRESSIN  CC/HR.    |  	  | carevue |   inputevents_cv   | Free Form Intake |                        
vasopressin unit/min   |   	  | carevue |   inputevents_cv   | Free Form Intake |                                  
```

However, there are three possible entries.

Would you please let me know how I can identify which one or all entries in mimic iii correspond to Vasopressin in mimic ii?

Thank you in advance.

**Comment by alistairewj** [comment]
There are two parts to the answer.

First, the exact same ITEMID for D_MEDITEMS can be found by adding 30000 - here is a useful table (which will go up on the website shortly):

MIMIC-II source | Old range | New range | Offset
--- | --- | --- | ---
D_CHARTITEMS | 1 - 20009 | 1-20009 | *None*
D_MEDITEMS | 1 - 405 | 30001 - 30405 | + 30000
D_IOITEMS | 1 - 6807 | 40001 - 46807 | + 40000

Second, since MIMIC-III now contains patients from two ICU databases merged together, you will need to look for more than one `ITEMID`. In your example, you can extract `ITEMID = 30051` (30000 + 51) to get vasopressin, but you will *also* need to extract `ITEMID = 222315`, which is also vasopressin, but for the 'metavision' database (that is the meaning of the 'carevue' and 'metavision' values in the `DBSOURCE` column). If you want your concept to cover the entire database, it is necessary to have at least one `ITEMID` from 'carevue' and one from 'metavision' (though perhaps not sufficient). The Metavision `ITEMID` values are always > 220000.

Let me know if that answers your question.

**Comment by edwardluotw** [comment]
Thank you for answering my question.
If my understanding is correct, the last two rows of my post come from D_IOITEMS because their ITEMID are 42802 and 42273 respectively.

About the second answer, is it possible there are multiple similar medication entries exist between carevue and metavision? If it is the case, how to identify the mapping between two systems for the same medication?
Thank you.

**Comment by tompollard** [comment]
Thanks Edward,

> If my understanding is correct, the last two rows of my post come from D_IOITEMS because their ITEMID are 42802 and 42273 respectively.

This is correct. Note that both of these ITEMIDs appear to be very infrequently used:

```sql
SELECT count(*) 
FROM inputevents_cv 
WHERE itemid = 42273;

-- returns 35
```

```sql
SELECT count(*) 
FROM inputevents_cv 
WHERE itemid = 42802;

-- returns 12
```

> About the second answer, is it possible there are multiple similar medication entries existing between carevue and metavision? If it is the case, how to identify the mapping between two systems for the same medication?

We have not yet attempted to consolidate identifiers across the two systems, so a single concept is likely have multiple ITEMIDs. To ensure that you are including all of the appropriate ITEMIDs in an analysis, we recommend carefully exploring the ITEMID labels in collaboration with a physician.

**Comment by edwardluotw** [comment]
Thanks a lot for the prompt reply.
